<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; (Kurz)Einführung in R – Data Mining Übungsmaterial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02_Lineare_Regression.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-K9CJ1KN8ZH"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K9CJ1KN8ZH', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_Einfuehrung.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">(Kurz)Einführung in R</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Mining Übungsmaterial</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Einfuehrung.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">(Kurz)Einführung in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Lineare_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Wichtige_Konzepte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Weiterführende Konzepte des Dataminings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Regressions_Baeume.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regressionsbäume</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#installieren-von-r-und-rstudio" id="toc-installieren-von-r-und-rstudio" class="nav-link active" data-scroll-target="#installieren-von-r-und-rstudio"><span class="header-section-number">1.1</span> Installieren von R und RStudio</a>
  <ul>
  <li><a href="#arbeiten-mit-arbeitspfaden-und-r-projekten" id="toc-arbeiten-mit-arbeitspfaden-und-r-projekten" class="nav-link" data-scroll-target="#arbeiten-mit-arbeitspfaden-und-r-projekten"><span class="header-section-number">1.1.1</span> Arbeiten mit Arbeitspfaden und R Projekten</a></li>
  </ul></li>
  <li><a href="#einfache-r-befehle-und-funktionen" id="toc-einfache-r-befehle-und-funktionen" class="nav-link" data-scroll-target="#einfache-r-befehle-und-funktionen"><span class="header-section-number">1.2</span> Einfache R Befehle und Funktionen</a>
  <ul>
  <li><a href="#vektoren-datensätze-und-rechenoperationen" id="toc-vektoren-datensätze-und-rechenoperationen" class="nav-link" data-scroll-target="#vektoren-datensätze-und-rechenoperationen"><span class="header-section-number">1.2.1</span> Vektoren, Datensätze und Rechenoperationen</a>
  <ul class="collapse">
  <li><a href="#vektoren" id="toc-vektoren" class="nav-link" data-scroll-target="#vektoren"><span class="header-section-number">1.2.1.1</span> Vektoren</a></li>
  <li><a href="#erstellen-von-datensätzen" id="toc-erstellen-von-datensätzen" class="nav-link" data-scroll-target="#erstellen-von-datensätzen"><span class="header-section-number">1.2.1.2</span> Erstellen von Datensätzen</a></li>
  <li><a href="#rechenoperationen-in-r" id="toc-rechenoperationen-in-r" class="nav-link" data-scroll-target="#rechenoperationen-in-r"><span class="header-section-number">1.2.1.3</span> Rechenoperationen in R</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#arbeiten-mit-datensätzen" id="toc-arbeiten-mit-datensätzen" class="nav-link" data-scroll-target="#arbeiten-mit-datensätzen"><span class="header-section-number">1.3</span> Arbeiten mit Datensätzen</a>
  <ul>
  <li><a href="#daten-importieren" id="toc-daten-importieren" class="nav-link" data-scroll-target="#daten-importieren"><span class="header-section-number">1.3.1</span> Daten Importieren</a></li>
  <li><a href="#sec-essentials" id="toc-sec-essentials" class="nav-link" data-scroll-target="#sec-essentials"><span class="header-section-number">1.3.2</span> Einfache Datenmanipulation und Visualisierung</a>
  <ul class="collapse">
  <li><a href="#anpassen-der-variablen" id="toc-anpassen-der-variablen" class="nav-link" data-scroll-target="#anpassen-der-variablen"><span class="header-section-number">1.3.2.1</span> Anpassen der Variablen</a></li>
  </ul></li>
  <li><a href="#anpassen-von-datensätzen" id="toc-anpassen-von-datensätzen" class="nav-link" data-scroll-target="#anpassen-von-datensätzen"><span class="header-section-number">1.3.3</span> Anpassen von Datensätzen</a>
  <ul class="collapse">
  <li><a href="#die-mutatefunktion" id="toc-die-mutatefunktion" class="nav-link" data-scroll-target="#die-mutatefunktion"><span class="header-section-number">1.3.3.1</span> Die <code>mutate</code>Funktion</a></li>
  <li><a href="#sec-pipe" id="toc-sec-pipe" class="nav-link" data-scroll-target="#sec-pipe"><span class="header-section-number">1.3.3.2</span> Der Pipe Operator <code>%&gt;%</code></a></li>
  <li><a href="#sec-filtering" id="toc-sec-filtering" class="nav-link" data-scroll-target="#sec-filtering"><span class="header-section-number">1.3.3.3</span> Filtern, Gruppieren und Zusammenfassen von Datasets</a></li>
  </ul></li>
  <li><a href="#faktor-variablen" id="toc-faktor-variablen" class="nav-link" data-scroll-target="#faktor-variablen"><span class="header-section-number">1.3.4</span> Faktor Variablen</a></li>
  </ul></li>
  <li><a href="#datenvisualisierung-mit-ggplot2" id="toc-datenvisualisierung-mit-ggplot2" class="nav-link" data-scroll-target="#datenvisualisierung-mit-ggplot2"><span class="header-section-number">1.4</span> Datenvisualisierung mit <code>{ggplot2}</code></a></li>
  <li><a href="#übungsaufgaben" id="toc-übungsaufgaben" class="nav-link" data-scroll-target="#übungsaufgaben"><span class="header-section-number">1.5</span> Übungsaufgaben</a>
  <ul>
  <li><a href="#r-als-taschenrechner" id="toc-r-als-taschenrechner" class="nav-link" data-scroll-target="#r-als-taschenrechner"><span class="header-section-number">1.5.1</span> R als Taschenrechner</a></li>
  <li><a href="#listen-und-vektoren" id="toc-listen-und-vektoren" class="nav-link" data-scroll-target="#listen-und-vektoren"><span class="header-section-number">1.5.2</span> Listen und Vektoren</a></li>
  <li><a href="#datensätze" id="toc-datensätze" class="nav-link" data-scroll-target="#datensätze"><span class="header-section-number">1.5.3</span> Datensätze</a></li>
  <li><a href="#grafiken" id="toc-grafiken" class="nav-link" data-scroll-target="#grafiken"><span class="header-section-number">1.5.4</span> Grafiken</a></li>
  </ul></li>
  <li><a href="#lösungen" id="toc-lösungen" class="nav-link" data-scroll-target="#lösungen"><span class="header-section-number">1.6</span> Lösungen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">(Kurz)Einführung in R</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Eine vollumfängliche Wiederholung von R Konzepten welche im Grundstudium gelehrt werden würden den Rahmen dieses Manuskriptes Sprengen. Wir werden deshalb in dieser Übung den Fokus auf die Installation von R, RStudio, wichtigen Libraries und deren grundlegende Anwendung legen. Für eine Umfangreiche Einfürung in R kann ich das <a href="https://yards.albert-rapp.de/">YARDS</a> Manuskript von Albert Rapp empfehlen.</p>
<section id="installieren-von-r-und-rstudio" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="installieren-von-r-und-rstudio"><span class="header-section-number">1.1</span> Installieren von R und RStudio</h2>
<p>In diesem Abschnitt wiederholen wir kurz die Installation von R und RStudio. Obwohl R (die Programmiersprache) mit einer vorinstallierten grafischen Benutzeroberfläche (GUI) installiert werden kann, werden wir stattdessen RStudio. RStudio kommt mit einigen Vorteilen gegenüber der internen R Gui, wie zum Beispiel das einsehen von Variablenwerten, Plots und Programmcode gleichzeitig. Es ist allerdings wichtig zu beachten, dass RStudio nur dann funktioniert, wenn R zuvor auch installiert wurde.</p>
<ul>
<li><p>R (für Windows) kann <a href="https://cran.r-project.org/bin/windows/base/">hier</a> heruntergeladen werden.</p></li>
<li><p>RStudio kann <a href="https://posit.co/download/rstudio-desktop/">hier</a> heruntergeladen werden.</p></li>
</ul>
<p>Nach der erfolgreichen Installation von R und RStudio sollte sich beim Start von RStudio ein Fenster öffnen, das in etwa so aussieht wie das folgende (vgl. <a href="https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html">RStudio User Guide</a>).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/rstudio-panes-labeled.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Das <em>Source</em> Panel zeigt ein <code>.R</code> File namens <code>ggplot2.R</code>. <code>.R</code> Dateien sind das standard R Format in welchen Code geschrieben und gespeichert wird. Eine ästhetischere Variante sind sogenannte Quarto Markdown Files (Endung .qmd) welche erlauben Text und Code zu kombinieren. Zum Beispiel wurde dieses Manuskript komplett mit Quarto geschrieben 😁 .</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Kurzeinführung Quarto">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kurzeinführung Quarto
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Quarto ist in RStudio bereits vorinstalliert, weshalb das Anlegen von neuen Dokumenten sehr leicht ist.</p>
<ol type="1">
<li><p>In RStudio, clicke auf <code>New File -&gt; Quarto Document...</code> im File <code>File</code> tab <img src="pictures/Quarto-Creation.png" class="img-fluid quarto-figure quarto-figure-center"></p></li>
<li><p>Wenn das <code>New Quarto Document</code> Fenster sich öffnet kann man das Outputformat wählen. Das HTML output ist sehr umgänglich und kann mit jedem Browser verwendet werden. Durch das auswählen des <code>create</code> Knopfes öffnet sich dann ein neues Quarto Dokument. <img src="pictures/Quarto-Creation-02.png" class="img-fluid quarto-figure quarto-figure-center"></p></li>
<li><p>Im Source Panel wird nun ein Quarto-Beispieldokument angezeigt, welches bearbeitet werden kann. Eventuell muss noch <code>rmarkdown</code> installiert werden, um eine korrekte Darstellung erzeugen zu können (vgl. Markierung 1). Das Quarto-Dokument kann dann durch Anklicken der entsprechenden Abschnitte geändert werden. R-Code-Zellen können durch Klicken auf den grünen Pfeil ausgeführt werden (vgl. Markierung 2). Um neue R-Code-Zellen zwischen Absätzen einzufügen, kann über die die Registerkarte <code>Einfügen</code> <code>Ausführbare Zelle -&gt; R</code> (vgl. Markierung 3) eine neue Code-Zelle . <img src="pictures/Quarto-Creation-03.png" class="img-fluid quarto-figure quarto-figure-center"></p></li>
</ol>
<p>Für weitere Informationen siehe z.B. <a href="https://quarto.org/docs/get-started/hello/rstudio.html">Quarto Guide</a>.</p>
</div>
</div>
</div>
<p>Natürlich muss man sich nicht zwingend in Quarto einlesen und kann die folgenden Aufgaben auch in normalen <code>.R</code> Skripten ausführen.</p>
<section id="arbeiten-mit-arbeitspfaden-und-r-projekten" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="arbeiten-mit-arbeitspfaden-und-r-projekten"><span class="header-section-number">1.1.1</span> Arbeiten mit Arbeitspfaden und R Projekten</h3>
<p>Nach dem Öffnen von RStudio kann durch den Befehl <code>getwd()</code> im Konsolen Panel der Pfad des aktuellen Arbeitsverzeichnis ausgegeben werden. Das Arbeitsverzeichnis ist zum Beispiel dann wichtig, wenn wir neue Datein anlegen, oder Datensätze einlesen wollen. Wenn der Rückgabewert des Befehls <code>getwd()</code> zum Beispiel <code>"C:/Users/lachlinu/Documents/Vorlesungen/Data_Mining/"</code> lautet, kann R auf jede Datei im Verzeichnis <code>Data_Mining</code> zugreifen. Eine Möglichkeit, das Arbeitsverzeichnis zu ändern, ist die Verwendung des Befehls <code>setwd()</code>. Hierbei ist wichtig, entweder den absoluten neuen Pfad, oder den relativen neuen Pfad anzugeben. Falls das Ziel ist, in das <code>/Documents</code> Verzeichnis zu wechseln, so kann man durch die Angabe des relativen Pfades <code>setwd('../../../')</code> das Verzeichnis <code>/Documents</code> auswählen, sofern das aktuelle Verzeichnis <code>"C:/Users/lachlinu/Documents/Vorlesungen/Data_Mining/"</code> ist. Die <code>../</code> Notation wird verwendet um das übergeordnete Verzeichnis auszuwählen. Alternativ kann man auch einfach den absoluten Pfad <code>"C:/Users/lachlinu/Documents"</code> in den <code>setwd()</code> Befehl einfügen um das Verzeichnis entsprechend zu wechseln. Das manuelle Ändern des Verzeichnisses in jedem <code>.R</code> Skript kann schnell mühsam werden, daher ist die Einrichtung eines Projekts eine praktischere Alternative. RStudio-Projekte ermöglichen die Erstellung eines individuellen Arbeitsverzeichnisses für mehrere Kontexte. Zum Beispiel können wir R nicht nur zum Lösen von Aufgaben für Data Mining verwenden, sondern auch für Abschlussarbeiten. Wenn man also zwei verschiedene Projekte einrichtet, kann man die Arbeitsverzeichnisse und Arbeitsbereiche für jedes Projekt individuell organisieren.</p>
<p>Das folgende Beispiel illustriert wie man ein Projekt einrichtet und verwendet:</p>
<ol type="1">
<li><p>Über den <code>File</code> Tab, wähle <code>New Project...</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/New_Project.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div></li>
<li><p>Durch das wählen von <code>Existing Directory</code> kann man durch den Explorer ein Verzeichnis wählen welches bereits existiert und dann durch den <code>Create Project</code> button ein neus Projekt in diesem Verzeichnis anlegen.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/New_Project_03.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div></li>
<li><p>Das neue Projekt kann dann einfach angeklickt werden, wodurch sich ein neues RStudio Fenster öffnen sollte.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/New_Project_04.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div></li>
</ol>
<p>Sobald sich über das anklicken des Projekts ein neues RStudio Fenster geöffnet hat wird durch das Ausführens des <code>getwd()</code> Befehls der Arbeitspfad des Projekts ausgegeben. Nun kann auch jede Datei in diesem Verzeichnis direkt verwendet werden.</p>
</section>
</section>
<section id="einfache-r-befehle-und-funktionen" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="einfache-r-befehle-und-funktionen"><span class="header-section-number">1.2</span> Einfache R Befehle und Funktionen</h2>
<p>Nach der erfolgreichen Installation von R und RStudio widmen wir uns nun ein paar grundlegenden Programmierkonzepten in R.</p>
<section id="vektoren-datensätze-und-rechenoperationen" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="vektoren-datensätze-und-rechenoperationen"><span class="header-section-number">1.2.1</span> Vektoren, Datensätze und Rechenoperationen</h3>
<section id="vektoren" class="level4" data-number="1.2.1.1">
<h4 data-number="1.2.1.1" class="anchored" data-anchor-id="vektoren"><span class="header-section-number">1.2.1.1</span> Vektoren</h4>
<p>Variablen wie Vektoren, oder Arrays werden in R mit dem <code>&lt;-</code> erstellt. Falls zum Beispiel das Ziel ist, einen Vektor zu erstellen, welcher die Werte <span class="math inline">\(1,2,3,4,5\)</span> enthält, gibt es viele Verschiedene Möglichkeiten dies zu erreichen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Jeder der obigen Vektoren enthält die Zahlen 1-5. <code>x1</code> wurde durch die <code>c()</code> Funktion erstellt, welche einen Vektor entsprechend der übergebenen Argumente erzeugt. <code>x2</code> wurde mithilfe des <code>:</code> Operators erstellt, welcher einer ganzzahlige Sequenz der Zahlen beginnend mit der Zahl links des Operators bis zur Zahl rechts des Operators erzeugt. Die Erzeugung des Vektors <code>x3</code> basiert auf der selben Idee wie die Erstellung des Vektors <code>x2</code>, allerdings wurde hier explizit die Funktion <code>seq</code> (Sequence) verwendet um die Zahlenfolge zu generieren. Die <code>seq</code> Funktion erlaubt im Gegensatz zur Verwendung des <code>:</code> Operators einige weitere Argumente wie zum Beispiel das Argument <code>by</code>, oder <code>length.out</code>.</p>
<p>Der folgende Befehl erzeugt beispielsweise eine Sequenz von 1 bis 5 mit Schrittgröße <span class="math inline">\(0.5\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>,<span class="at">to =</span> <span class="dv">5</span>,<span class="at">by =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0</code></pre>
</div>
</div>
<p>Durch das Spezifizieren von <code>length.out</code> kann man die Länge der Sequenz steuern. So wird im folgenden Beispiel eine Sequenz von Zahlen zwischen 1 und 5 erzeugt mit der Länge 20.</p>
<p>Die Zuweisung von Werten in Funktionen erfolgt im obigen Beispiel mit dem Symbol <code>=</code>. Die Zuweisung neuer Variablen außerhalb von Funktionen kann auch mit dem <code>=</code> Symbol erfolgen, aber es wird selten verwendet und außer in einigen pathologischen Fällen gibt es keinen Unterschied. Die meisten R-Benutzer bevorzugen jedoch die Zuweisung von Umgebungsvariablen mit <code>&lt;-</code>, was in Funktionsaufrufen <strong>nicht</strong> funktioniert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="at">length.out =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.000000 1.210526 1.421053 1.631579 1.842105 2.052632 2.263158 2.473684
 [9] 2.684211 2.894737 3.105263 3.315789 3.526316 3.736842 3.947368 4.157895
[17] 4.368421 4.578947 4.789474 5.000000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die Argumente einer Funktion müssen nicht immer übergeben werden. Im obigen Beispiel wurden die Bennenungen <code>"from="</code> und <code>"to="</code> weggelassen. Das weglassen der Argumentnamen beim Aufruf der Funktion ist lediglich der Faulheit der programmierenden Person geschuldet. In den meisten Fällen lohnt es sich Zwecks Lesbarkeit diese zu benennen.</p>
</div>
</div>
<p>Der Abstand zwischen den einzelnen Folgenglieder der Folge ist hierbei gegeben durch</p>
<p><span class="math display">\[
\frac{5-1}{20-1} = \frac{4}{19}.
\]</span> Im Zähler ist steht die Länge des Intervalls welche durch <code>obere Grenze - untere Grenze</code> berechnet wird und im Nenner <code>Anzahl der Folgeglieder - 1</code>.</p>
<p>Das Zugreifen auf Listenelemente wird durch eckige Klammern ermöglicht. Möchte man zum Beispiel auf das zweite Element des Vektors <code>x2</code> zugreifen, so wendet man die folgende Notation an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x2[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Innerhalb der eckigen Klammer steht der Index, bzw. die Indizes welche zurückgegeben werden sollen. So kann man auch zum Beispiel die ersten zwei Einträge des Vektors <code>x2</code> durch folgende Notation auswählen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x2[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2</code></pre>
</div>
</div>
</section>
<section id="erstellen-von-datensätzen" class="level4" data-number="1.2.1.2">
<h4 data-number="1.2.1.2" class="anchored" data-anchor-id="erstellen-von-datensätzen"><span class="header-section-number">1.2.1.2</span> Erstellen von Datensätzen</h4>
<p>Obwohl die meisten Datensätze, welche wir in der übung verwendet bereits erstellt wurden, ist es sehr sinnvoll sich mit der Erstellung von eigenen Datensätzen auseinander zu setzen. Besonders wenn man auf Basis bereits existierender Datensätze Teildatensätze erstellen will, ist diese Kenntnis hilfreich.</p>
<p>Ein Grundlegender Befehl zum erzeugen von Datensätzen ist die <code>data.frame</code> Funktion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="at">length.out =</span> <span class="dv">18</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">18</span>],</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> <span class="fu">unlist</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">rep</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">strsplit</span>(<span class="st">"The quick brown fox jumps over the lazy dog"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">split =</span> <span class="st">" "</span>),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>          <span class="dv">2</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das Datensatz <code>data</code> enthält drei Spalten: <code>x,y,z</code> welche mit verschiedenen Werten erzeugt wurden. Die Spalte <code>x</code> wurde mithilfe der <code>seq</code> Funktion mit 18 Werten befüllt welche zwischen <span class="math inline">\(1\)</span> und <span class="math inline">\(10\)</span> liegen. Die Spalte <code>y</code> wurde mithilfe des vordefinierten <code>letters</code> Vektor befüllt. Dieser enthält die Buchstaben <code>a-z</code>. Hierbei wurden ebenso die 18 Einträge verwendet. In der letzten Spalte <code>z</code> wurden mehrere Funktionen verschachtelt auf einmal verwendet. Die innerste Funktion <code>strsplit</code> teilt einen gegebenen String (<code>&lt;chr&gt;</code>) Vektor in einzelne Komponenten auf. Die Teilung des langen Strings folgt durch das Argument <code>split</code>. Hier wurde als Split Argument das Leerzeichen <code>" "</code> übergeben. Dadurch wird der Satz <code>"The quick brown fox jumps over the lazy dog"</code> an jedem Leerzeichen getrennt und eine Liste der einzelnen Wörter zurückgegeben. Die <code>rep</code> (Repeat) Funktion wiederholt das übergebene Argument und wiederholt dieses gemäß der übergebnen Zahl. Da der Rückgabewert der <code>rep</code> Funktion in diesem Fall eine verschachtelte Liste ist (eine Liste mit zwei Elementen, wobei jedes dieser beiden Elemente wieder selbst eine Liste ist), wir die Verschachtelung über die <code>unlist</code> funktion aufgehoben.</p>
<p>Der Datensatz hat somit folgende Struktur:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x y     z
1   1.000000 a   The
2   1.529412 b quick
3   2.058824 c brown
4   2.588235 d   fox
5   3.117647 e jumps
6   3.647059 f  over
7   4.176471 g   the
8   4.705882 h  lazy
9   5.235294 i   dog
10  5.764706 j   The
11  6.294118 k quick
12  6.823529 l brown
13  7.352941 m   fox
14  7.882353 n jumps
15  8.411765 o  over
16  8.941176 p   the
17  9.470588 q  lazy
18 10.000000 r   dog</code></pre>
</div>
</div>
<p>Die Variablen eines Datensatzes könne über verschiedene Methoden ausgewählt und bearbeitet werden. Im nächsten Abschnitt werden hierfür einige dieser Methoden vorgestellt.</p>
</section>
<section id="rechenoperationen-in-r" class="level4" data-number="1.2.1.3">
<h4 data-number="1.2.1.3" class="anchored" data-anchor-id="rechenoperationen-in-r"><span class="header-section-number">1.2.1.3</span> Rechenoperationen in R</h4>
<p>R wurde ursprünglich als statistische Programmiersprache eingeführt, weshalb bereits viele Funktionen zum berechnen verschiedener Werte vordefiniert sind.</p>
<p>Arithmetische Rechenoperation funktionieren für Zahlenwerte, Zahlenvektoren und auch gemischten Vektoren.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span><span class="sc">+</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)<span class="sc">*</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  4  6  8 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  4  9 16 25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cos</span>(<span class="fu">seq</span>(<span class="dv">0</span>,pi,<span class="at">length.out=</span><span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.0000000  0.9396926  0.7660444  0.5000000  0.1736482 -0.1736482
 [7] -0.5000000 -0.7660444 -0.9396926 -1.0000000</code></pre>
</div>
</div>
<p>Obige Beispiele enthalten nur eine kleine Selektion an Methoden welche verwendet werden können, um verschiedene Rechenoperationen durchzuführen. R Funktioniert gewissermaßen teilweise wie ein Taschenrechner, weshalb dieser Abschnitt auch nicht in der Tiefe ausgeführt werden muss.</p>
</section>
</section>
</section>
<section id="arbeiten-mit-datensätzen" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="arbeiten-mit-datensätzen"><span class="header-section-number">1.3</span> Arbeiten mit Datensätzen</h2>
<p>Im Zusammenhang mit Data Mining bilden Daten die Grundlage. Egal ob das Ziel ist das Wetter, künftige Aktienkurse oder die Grundmiete einer potenziellen Mietwohnung vorherzusagen - ohne hochwertige Daten versagen selbst die fortschrittlichsten Modelle. Die Realität sieht jedoch so aus, dass Daten, die wir aus dem Internet, von Servern oder aus Excel Tabellen beziehen, oft alles andere als makellos sind. So können fehlende Werte beispielsweise als <code>NA</code> (Not Available), <code>NaN</code> (Not a Number), <code>NULL</code> oder einfach als leere Zeichenkette <code>„“</code> kodiert sein. Aus diesem Grund ist es wichtig, dass die grundlegenden Datenmanipulationen in R nochmals diskutier werden.</p>
<section id="daten-importieren" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="daten-importieren"><span class="header-section-number">1.3.1</span> Daten Importieren</h3>
<p>Viele Datensätze sind zwar bereits in R integriert, bzw. können über Libraries eingelesen werden, allerdings sind einige der Datesätze welche wir in der Übung verwenden nur durch externe Quellen verfïugbar. Die meisten Daten werden im <code>csv</code> oder <code>txt</code> Format zur Verfügung gestellt. Es ist deshalb wichtig zu verstehen wie man diese Datensätze einliest bevor man tatsächlich mit diesen arbeitet.</p>
<p>Für die folgenden Übungen werden wir das Ramen Dataset untersuchen, welches entweder von der Data Science Plattform <a href="https://www.kaggle.com/datasets/residentmario/ramen-ratings">Kaggle</a> oder dem untenstehenden Button heruntergeladen werden kann.</p>
<div style="text-align: center;">
<p><a href="data/ramen-ratings.csv" class="btn btn-outline-primary" role="button" data-toggle="tooltip" title="3.3 MB">Download ramen Data</a></p>
</div>
<p>Der Ramen Datensatz enthält Informationen über verschiedene Instant Ramen gerichte, welche besonders beliebt unter Studierenden während der Prüfungszeit sind.</p>
<p>Die Daten können dann zum Beispiel in einem Verzeichnis <code>Daten</code> gespeichert werden, welches im gleichen Verzeichnis liegt wie die Projektdatei. Um die Daten einzulesen verwendet man in diesem Fall die <code>read.csv</code> Funktion verwenden. Im folgenden Code Snippet wird der Ramen Datensatz aus dem Verzeichnis <code>/data</code> eingelesen und unter dem Namen <code>data_ramen</code> gespeichert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/ramen-ratings.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-essentials" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="sec-essentials"><span class="header-section-number">1.3.2</span> Einfache Datenmanipulation und Visualisierung</h3>
<p>Für die meisten Übungen werden wir das <code>{tidyverse}</code> verwenden, welches eine Sammlung von Libraries enthält die das Arbeiten mit Daten stark vereinfachen. Um die Sammlung von Libraries zu installieren, kann der <code>install.packages()</code> Befehl verwendet werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nach der Installation kann die Library dann mit dem <code>library</code> Befehl zur aktuellen R Session hinzugefügt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Das <code>{tidyverse}</code> enthält eine vielzahl wichtiger Libraries, von welchen wir vor allem die folgenden drei verwenden werden:</p>
<ul>
<li><code>{ggplot2}</code> für das Erstellen von Grafiken,</li>
<li><code>{dplyr}</code> für Datenmanipulation,</li>
<li><code>{tibble}</code> für das effiziente Speichern von Daten.</li>
</ul>
<p>Eine sehr gute Einführung in diese Library kann unter folgendem <a href="https://www.tidyverse.org/">Link</a> eingesehen werden. Der Entwickler hinter der Library hat ebenso ein kostenloses Buch namens <a href="https://r4ds.hadley.nz/">R for Data Science</a> geschrieben, welches eine sehr Umfangreiche Einführung in die verschiedenen Libraries des <code>{tidyverse}</code> gibt.</p>
<p>Nach dem erfolreichen Installieren und hinzufügen der Library können wir direkt die erste essentielle Funktion nutzen. Die <code>glimpse()</code> Funktion gibt einen kompakten überblick über den Inhalt und die beinhaltenden Datentypen des unterliegenden Datensatzes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_ramen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,580
Columns: 7
$ Review.. &lt;int&gt; 2580, 2579, 2578, 2577, 2576, 2575, 2574, 2573, 2572, 2571, 2…
$ Brand    &lt;chr&gt; "New Touch", "Just Way", "Nissin", "Wei Lih", "Ching's Secret…
$ Variety  &lt;chr&gt; "T's Restaurant Tantanmen ", "Noodles Spicy Hot Sesame Spicy …
$ Style    &lt;chr&gt; "Cup", "Pack", "Cup", "Pack", "Pack", "Pack", "Cup", "Tray", …
$ Country  &lt;chr&gt; "Japan", "Taiwan", "USA", "Taiwan", "India", "South Korea", "…
$ Stars    &lt;chr&gt; "3.75", "1", "2.25", "2.75", "3.75", "4.75", "4", "3.75", "0.…
$ Top.Ten  &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…</code></pre>
</div>
</div>
<p><code>Rows: 2,580</code> bedeutet, dass der Datensatz 2.580 Einträge hat, und <code>Columns: 7</code> bedeutet, dass der Datensatz jeweils 7 Variablen enthält. Die erste Spalte enthält die Variablennamen, ihre Datentypen und einige Anfangswerte, wodurch der Datensatz eine klare Struktur erhält. Wir können bereits sehen, dass außer einer Variablen (<code>Review</code>) jede andere Variable vom Typ <code>chr</code> ist, was für <em>character</em> oder <em>string</em> steht.</p>
<section id="anpassen-der-variablen" class="level4" data-number="1.3.2.1">
<h4 data-number="1.3.2.1" class="anchored" data-anchor-id="anpassen-der-variablen"><span class="header-section-number">1.3.2.1</span> Anpassen der Variablen</h4>
<p>Beim Aufrufen der <code>glimpse()</code> Funktion ist direkt aufgefallen, dass die Variablennamen teilweise inkonsistent sind. Die erste Spalte hat zum Beispiel den Namen <code>"Review.."</code>. Um eine konsistente und einfache Namengebung zu verwenden, können wir die <code>janitor::clean_names</code> Funktion verwenden.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die obige Notation wird verwendet, wenn man zusätzlich zum Funktionsname auch noch die Library der Funktion benennen will. Besonders bei der vermeidung von sogenannten ‘namespace conflicts’, bei welchen zwei Funktionen aus verschiedenen Libraries die gleichen Namen besitzen.</p>
</div>
</div>
<p>Auch hier gilt: Eventuell muss die <code>{janitor}</code> Library zuerst installiert werden, bevor die Funktion verwendet werden kann. Die Installation kann analog wie im Beispiel zur <code>{tidyverse}</code> Library durchgeführt werden.</p>
<p>Wenn die Library dann erfolgreich installiert wurde, können wir die Daten mit einer angepassten Version überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="ot">&lt;-</span> janitor<span class="sc">::</span><span class="fu">clean_names</span>(<span class="at">dat =</span> data_ramen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nach dem Abändern der Daten und einem erneuten Aufrufen der <code>glimpse()</code> Funktion kann die Änderung der Variablennamen eingesehen werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_ramen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,580
Columns: 7
$ review  &lt;int&gt; 2580, 2579, 2578, 2577, 2576, 2575, 2574, 2573, 2572, 2571, 25…
$ brand   &lt;chr&gt; "New Touch", "Just Way", "Nissin", "Wei Lih", "Ching's Secret"…
$ variety &lt;chr&gt; "T's Restaurant Tantanmen ", "Noodles Spicy Hot Sesame Spicy H…
$ style   &lt;chr&gt; "Cup", "Pack", "Cup", "Pack", "Pack", "Pack", "Cup", "Tray", "…
$ country &lt;chr&gt; "Japan", "Taiwan", "USA", "Taiwan", "India", "South Korea", "J…
$ stars   &lt;chr&gt; "3.75", "1", "2.25", "2.75", "3.75", "4.75", "4", "3.75", "0.2…
$ top_ten &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""…</code></pre>
</div>
</div>
</section>
</section>
<section id="anpassen-von-datensätzen" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="anpassen-von-datensätzen"><span class="header-section-number">1.3.3</span> Anpassen von Datensätzen</h3>
<section id="die-mutatefunktion" class="level4" data-number="1.3.3.1">
<h4 data-number="1.3.3.1" class="anchored" data-anchor-id="die-mutatefunktion"><span class="header-section-number">1.3.3.1</span> Die <code>mutate</code>Funktion</h4>
<p>Um Anpassungen an den Daten vorzunehmen, bietet sich die <code>dplyr::mutate</code> Funktion perfekt an.</p>
<p>Die <code>mutate</code> Funktion kann entweder neue Spalten generieren, oder vorhandene Spalten modifizieren. Im folgenden Beispiel wird die <code>mutate</code> Funktion dafür verwendet die Variable <code>stars</code> vom Datentyp <code>&lt;chr&gt;</code> in <code>&lt;dbl&gt;</code> umzuwandeln und die Variable <code>top_ten</code> zu entfernen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>data_ramen <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2"></a>  <span class="fu">mutate</span>(</span>
<span id="cb30-3"><a href="#cb30-3"></a>    <span class="at">stars =</span> <span class="fu">as.double</span>(stars),</span>
<span id="cb30-4"><a href="#cb30-4"></a>    <span class="at">top_ten =</span> <span class="cn">NULL</span></span>
<span id="cb30-5"><a href="#cb30-5"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `stars = as.double(stars)`.
Caused by warning:
! NAs durch Umwandlung erzeugt</code></pre>
</div>
</div>
<ol type="1">
<li><p>In der ersten Zeile der Codezelle wird angegeben, dass der Datensatz <code>data_ramen</code> durch eine veränderte Version überschrieben werden soll.</p></li>
<li><p>Der ursprüngliche Datensatz <code>data_ramen</code> wird in der zweiten Zeile an die <code>mutate</code>Funktion übergeben.</p></li>
<li><p>In der dritten Zeile wird als erstes Argument die Variable <code>stars</code> durch die Ausgabe der Funktion <code>as.double</code> mit Argument <code>stars</code> überschrieben. Die Funktion <code>as.double</code> ist eine Funktion der <code>{base}</code> library.</p></li>
<li><p>In der vierten Zeile wird als weiteres Argument (separiert durch ein <code>,</code> aus der vorherigen Zeile) die den Variable <code>top_ten</code> entfertn, indem die Variable mit <code>NULL</code> überschrieben wird.</p></li>
</ol>
<p>Das ausführen der vorherigen Code Zelle wirft folgende Warnung:</p>
<blockquote class="blockquote">
<p>Warning message: There was 1 warning in <code>mutate()</code>. i In argument: <code>stars = as.double(stars)</code>. Caused by warning: ! NAs introduced by coercion</p>
</blockquote>
<p>Dies liegt daran, dass in der Variable <code>stars</code> fehlende Werte vorhanden sind. Durch das Anwenden der <code>as.double</code> Funktion wurden die Fehlenden werte in <code>NA</code> Werte umgewandelt, was aber erstmal kein Problem darstellt.</p>
</section>
<section id="sec-pipe" class="level4" data-number="1.3.3.2">
<h4 data-number="1.3.3.2" class="anchored" data-anchor-id="sec-pipe"><span class="header-section-number">1.3.3.2</span> Der Pipe Operator <code>%&gt;%</code></h4>
<p>In der Code Zelle</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>data_ramen <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">mutate</span>(...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>wurde in der ersten Zeile der sogenannte Pipe Operator <code>%&gt;%</code> verwendet. Der Pipe Operator ist ein mächtiges Werkzeug aus der <code>{magittr}</code> Library welche erlaubt Verkettungen von Funktionen durchzuführen. Die Wortwörtliche übersetzung “Rohr” steht hierbei sinnbildlich für den Vorgang dass auf der einen Seite (links) z.B. Daten übergeben werden und auf der anderen Seite (rechts) nach den durchgeführten Transformationen ausgegeben werden. Die Stärke des Operators liegt hierbei in der Möglichkeit viele Operationen sequentiell durchzuführen und dabei die Lesbarkeit und Übersichtlichkeit zu bewahren.</p>
<p>So kann man zum Beispiel nach der initialen Transformation durch die <code>mutate</code> Funktion die <code>na.omit</code> Funktion auf die resultierenden Daten angewendet werden, um alle <code>NA</code>, bzw. <code>NaN</code> Werte zu entfernen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">stars =</span> <span class="fu">as.double</span>(stars),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">top_ten =</span> <span class="cn">NULL</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Durch die Anwendung des Pipe Operators muss auch der Datensatz im Obigen Beispiel nicht als Argument der Funktion übergeben werden. Ohne den Pipe Operator könnte man das obige Beispiel auch wie folgt implementieren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="ot">&lt;-</span> <span class="fu">mutate</span>(<span class="fu">na.omit</span>(data_ramen),</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">stars =</span> <span class="fu">as.double</span>(stars),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">top_ten =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-filtering" class="level4" data-number="1.3.3.3">
<h4 data-number="1.3.3.3" class="anchored" data-anchor-id="sec-filtering"><span class="header-section-number">1.3.3.3</span> Filtern, Gruppieren und Zusammenfassen von Datasets</h4>
<p>Im vorherigen Abschnitt haben wir uns mit grundlegenden Funktionen für das Anpassen der Daten beschäftigt. Ein weiterer wichtiger Aspekt beim Umgang mit Daten ist die sogenannte Explorative Datenanalyse (EDA). Hierbei werden die unterliegenden Daten mithilfe von deskriptiven und induktiven Methoden untersucht. Wichtige Funktionen in diesem Kontext sind die <code>filter</code>, <code>group_by</code> und <code>summarise</code> Funktionen aus dem <code>{dplyr}</code> Package.</p>
<p>Angenommen wir wollen für das <code>data_ramen</code> Dataset herausfinden, wie viele Marken (brands) mehr als 30 Sorten (varieties) an Instant Ramen Nudeln anbieten. Intuitiv macht es Sinn die Einträge des Datensatzes zu Gruppieren, wobei jede Marke einer Gruppe entspricht. Nach der Bildung von Gruppen erzeugt durch die Marken, kann dann für jede Gruppe die Anzahl der Einträge innerhalb der Gruppen berechnet werden. Abschließend filtert man die resultierenden Ergebnisse nach dem Kriterium, dass mindestens 30 Einträge in einer Gruppe enthalten sein müssen. Diese beschriebene Heuristik lässt sich mithilfe des folgenden Skripts umsetzen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">group_by</span>(brand) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3"></a>  <span class="fu">summarise</span>(<span class="at">num_var =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4"></a>  <span class="fu">filter</span>(num_var <span class="sc">&gt;</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   brand         num_var
   &lt;chr&gt;           &lt;int&gt;
 1 Indomie            53
 2 Lucky Me!          34
 3 Mama               71
 4 Maruchan           76
 5 Myojo              63
 6 Nissin            381
 7 Nongshim           98
 8 Ottogi             45
 9 Paldo              66
10 Samyang Foods      51
11 Vifon              33
12 Vina Acecook       34</code></pre>
</div>
</div>
<p>Fassen wir die Schritte im obigen Skript nochmal zusammen:</p>
<ol type="1">
<li><p>In der ersten Zeile wird der Datensatz <code>data_ramen</code> durch den Pipe Operator in die folgenden Funktionen übergeben.</p></li>
<li><p>In der zweiten Zeile wird der <code>group_by</code> Befehl verwendet um die Einträge des Datensatzes nach der Variable <code>brand</code> zu Gruppieren.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Durch das alleinige Aufrufen der <code>group_by</code> Funktion mit der entsprechenden Gruppierungsvariable als Argument, wird im Output bereits angezeigt wie viele verschiednen Gruppen erstellt wurden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(brand) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,577
Columns: 6
Groups: brand [355]
$ review  &lt;int&gt; 2580, 2579, 2578, 2577, 2576, 2575, 2574, 2573, 2572, 2571, 25…
$ brand   &lt;chr&gt; "New Touch", "Just Way", "Nissin", "Wei Lih", "Ching's Secret"…
$ variety &lt;chr&gt; "T's Restaurant Tantanmen ", "Noodles Spicy Hot Sesame Spicy H…
$ style   &lt;chr&gt; "Cup", "Pack", "Cup", "Pack", "Pack", "Pack", "Cup", "Tray", "…
$ country &lt;chr&gt; "Japan", "Taiwan", "USA", "Taiwan", "India", "South Korea", "J…
$ stars   &lt;dbl&gt; 3.75, 1.00, 2.25, 2.75, 3.75, 4.75, 4.00, 3.75, 0.25, 2.50, 5.…</code></pre>
</div>
</div>
<p>so wurden im obigen Beispiel 355 verschiedene Gruppen gebildet, woraus wir schließen können, dass im Datensatz 355 verschiedene Marken enthalten sind (unter der Annahme, dass keine Duplikate enthalten sind).</p>
</div>
</div></li>
<li><p>Der <code>summarise</code> Befehl wird dann verwendet, um verschiedene Deskriptive Statistiken auf den Gruppen anzuwenden. In diesem Fall wird ähnlich wie bei der Verwendung der <code>mutate</code> Funktion eine neue Spalte <code>num_vars</code> erstellt welch in jeder Zeile den Output der Funktion <code>n</code> enthält. Die <code>dplyr::n</code> Funktion hat als Rückgabewert die Gruppengröße.</p></li>
</ol>
</section>
</section>
<section id="faktor-variablen" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="faktor-variablen"><span class="header-section-number">1.3.4</span> Faktor Variablen</h3>
<p>Ein wichtiger Datentyp, der sowohl ordinale (Daten mit einem gewissen Ordnungsbegriff) als auch nominale Daten verarbeiten kann, sind so genannte Faktor Variablen (Datentyp <code>&lt;fct&gt;</code>).</p>
<p>Betrachten wir hierfür den folgenden Synthetischen Datensatz mit sieben Personen mit entsprechenden Altersgruppen und Augenfarben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>data_example <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a> <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Alice"</span>, <span class="st">"Bob"</span>, <span class="st">"Charlie"</span>, <span class="st">"Diana"</span>, <span class="st">"Eve"</span>, <span class="st">"Frank"</span>, <span class="st">"Grace"</span>),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a> <span class="at">age_groups =</span> <span class="fu">c</span>(<span class="st">"18-25"</span>, <span class="st">"&lt;18"</span>, <span class="st">"26-35"</span>, <span class="st">"36-45"</span>, <span class="st">"18-25"</span>, <span class="st">"60+"</span>, <span class="st">"26-35"</span>),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a> <span class="at">eye_color =</span> <span class="fu">c</span>(<span class="st">"Blue"</span>, <span class="st">"Brown"</span>, <span class="st">"Green"</span>, <span class="st">"Hazel"</span>, <span class="st">"Brown"</span>, <span class="st">"Blue"</span>, <span class="st">"Green"</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>data_example </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  names   age_groups eye_color
  &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;    
1 Alice   18-25      Blue     
2 Bob     &lt;18        Brown    
3 Charlie 26-35      Green    
4 Diana   36-45      Hazel    
5 Eve     18-25      Brown    
6 Frank   60+        Blue     
7 Grace   26-35      Green    </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Im obigen Code Snippet wurde die <code>tibble::tibble</code> Funktion verwendet. Tibbles werden ähnlich wie <code>data.frame</code> Objekte zum speichern von Datensätzen verwendet. Tibbles haben allerdings zum Beispiel den Vorteil, dass sie bei der Ausgabe in der Konsole übersichtlicher dargestellt werden.</p>
</div>
</div>
<p>Da die Variable <code>age_group</code> nur eine Altersspanne angibt, ist es nicht sinnvoll, sie als Zahl und nicht als Ordinalvariable zu kodieren. Mit der Funktion <code>mutate</code> können wir deshalb die Altersgruppen als Ordinalvariablen (ordered factors) kodiert werden. Dazu wird die Variable <code>age_groups</code> in einen Faktor mit Stufen und Label gesetzt. Die Stufen geben die Reihenfolge der Werte an, und die Label können zur Umbenennung dieser Kategorien verwendet werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>data_example <span class="ot">&lt;-</span> data_example <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2"></a>  <span class="fu">mutate</span>( </span>
<span id="cb41-3"><a href="#cb41-3"></a>    <span class="at">age_groups =</span> <span class="fu">factor</span>(</span>
<span id="cb41-4"><a href="#cb41-4"></a>      age_groups,</span>
<span id="cb41-5"><a href="#cb41-5"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"&lt;18"</span>, <span class="st">"18-25"</span>, <span class="st">"26-35"</span>, <span class="st">"36-45"</span>, <span class="st">"60+"</span>),</span>
<span id="cb41-6"><a href="#cb41-6"></a>      <span class="at">ordered =</span> <span class="cn">TRUE</span>,</span>
<span id="cb41-7"><a href="#cb41-7"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"child"</span>,<span class="st">"adult"</span>,<span class="st">"adult"</span>,<span class="st">"adult"</span>,<span class="st">"senior"</span>)</span>
<span id="cb41-8"><a href="#cb41-8"></a>    )</span>
<span id="cb41-9"><a href="#cb41-9"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li><p>Ähnlich wie im vorherigen Beispiel sollten wir angeben, dass wir den Datensatz <code>data_example</code> mit einer veränderten Version überschreiben.</p></li>
<li><p>In der zweiten Zeile wird dann die <code>mutate</code> Funktion aufgerufen um in der dritten Zeile die Variabele <code>age_groups</code> zu überschreiben.</p></li>
<li><p>Durch das Setzen von <code>age_groups = factor(age_groups, ...)</code> wird die Variable <code>age_groups</code> in einen (bisher ungeordneten) Faktor umgewandelt, der das setzen von Stufen (<code>levels</code>) und Labels ermöglicht.</p></li>
<li><p>So wird durch das Setzen von <code>levels = c("&lt;18", "18-25",...)</code> eine Ordnung auf die Variable auferlegt.</p></li>
<li><p><code>ordered=TRUE</code> gibt an, dass die Altersgruppen nach den im <code>levels</code>Vektor angegebenen Stufen aufsteigend sortiert sind.</p></li>
<li><p>Zu guter Letzt gibt <code>labels = c("child", "adult", ...)</code> die Bezeichnungen an, welche die numerischen Altersgruppen ersetzen. Zum Beispiel wird <span class="math inline">\(&lt;18\)</span> als <code>"child"</code> bezeichnet, die Bereiche <code>18-25</code>, <code>26-35</code> und <code>36-45</code> als “adult“, und <span class="math inline">\(&gt;60\)</span> als <code>"senior"</code>.</p></li>
</ol>
<p>Analog kann auch die Variable <code>eye_color</code> in eine nominale Faktorvariable umgewandelt werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>data_example <span class="ot">&lt;-</span> data_example <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">eye_color =</span> <span class="fu">factor</span>(eye_color)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="datenvisualisierung-mit-ggplot2" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="datenvisualisierung-mit-ggplot2"><span class="header-section-number">1.4</span> Datenvisualisierung mit <code>{ggplot2}</code></h2>
<p>Ein weiterer wichtiger Aspekt des Data Minings ist die grafische Darstellung von Datensätzen. Die Beschreibung eines Algorithmus mit mathematischer Notation oder die Untersuchung eines Datensatzes mit Hilfe von deskriptiven und induktiven Statistiken allein kann eine Herausforderung für die Vermittlung von Botschaften darstellen. Obwohl R einige Basisfunktionen zur Erstellung von Grafiken bietet, wird in diesem Kurs hauptsächlich die Bibliothek <code>{ggplot2}</code> verwendet. Eine umfassende Einführung in <code>{ggplot2}</code> findet sich in Hadley Wickhams Buch <a href="https://ggplot2-book.org/">Elegant Graphics for Data Analysis</a>.</p>
<p>Für das folgende Beispiel wird der Datensatz <code>data_ramen_ratings</code> verwendet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>data_ramen_ratings <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(stars) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>data_ramen_ratings <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  stars count
  &lt;dbl&gt; &lt;int&gt;
1  0       26
2  0.1      1
3  0.25    11
4  0.5     14
5  0.75     1
6  0.9      1</code></pre>
</div>
</div>
<p>Hierbei wird ein neuer Datensatz erzeugt, welcher zwei Spalten enthält. Die erste Spalte enthält die verschiedenen Ausprägungen der Variable <code>stars</code> und die zweite Spalte <code>count</code> enthält die Anzahl der Ramen, welche die entsprechende Bewertung in <code>stars</code> haben. Der <code>head</code> Befehl gibt hierbei die ersten 6 Einträge des neu erstellten Datensatzes aus.</p>
<p>Eine mit <code>{ggplot2}</code> erstellte Grafik besteht aus den folgenden drei Grundkomponenten:</p>
<ol type="1">
<li><p>Die Daten selbst.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data_ramen_ratings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Beachte, dass das Diagramm so noch keine Achsen, Ticks und Variablen anzeigt.</p></li>
<li><p>Eine Reihe von <em>Ästhetik-Zuordnungen</em> (<em>aesthetics mappings</em>), die beschreiben, wie Variablen in den Daten auf visuelle Eigenschaften abgebildet werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stars,<span class="at">y=</span>count), <span class="at">data =</span> data_ramen_ratings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die <code>aes</code> Funktion gibt hierbei die Ästhetik-Zuordnung an. Im obigen Beispiel wird spezifiziert, dass die <span class="math inline">\(x\)</span>-Achse die Variable <code>stars</code> abbildet und die <span class="math inline">\(y\)</span>-Achse die Anzahl der Bewertungen.</p></li>
<li><p>Als nächstes werden durch die <em>geom</em>-Layer die grafischen Komponenten hinzugefügt, welche beschreiben wie die Daten in der Grafik repräsentiert werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stars, <span class="at">y=</span>count), <span class="at">data =</span> data_ramen_ratings)<span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Neben der <code>ggplot</code> Funktion wurde in der Obigen Zelle nun die Geometrie Column (Säule) hinzugefügt. Um eine neue Geometrie hinzuzufügen wird nicht wie bei den vorheringen Beispielen der Pipe Operator, sondern ein <code>+</code> verwendet. Der Funktion <code>geom_col</code> (Geometry Column) wurde kein weiteres Argument hinzugefügt. Man kann durch das Hinzufügen weiterer Argumente wie zum Beispiel <code>fill</code> (Füllung) die Farbe der Säulen verändern. So wird durch das Setzen von `fill=“red” die Farbe der Säulen auf rot gesetzt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stars, <span class="at">y=</span>count), <span class="at">data =</span> data_ramen_ratings)<span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Weitere Möglichkeiten die Grafiken anzupassen und die Daten auf verschiedene Arten darzustellen werden in den folgenden Übungen eingeführt.</p></li>
</ol>
</section>
<section id="übungsaufgaben" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="übungsaufgaben"><span class="header-section-number">1.5</span> Übungsaufgaben</h2>
<section id="r-als-taschenrechner" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="r-als-taschenrechner"><span class="header-section-number">1.5.1</span> R als Taschenrechner</h3>
<div id="exr-calc" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.1</strong></span> Geben Sie folgende Ausdrücke in die R-Console ein und erklären Sie jeweils das Ergebnis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">4</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>(<span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">4</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fl">0.2</span> <span class="sc">*</span> <span class="dv">3</span> <span class="sc">-</span> <span class="fl">1.1</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="dv">0</span>,<span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span> <span class="sc">-</span> <span class="fl">1.1</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span><span class="dv">3</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>(<span class="dv">2</span><span class="sc">^</span><span class="dv">3</span>)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">1</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fu">exp</span>(<span class="dv">1</span>))</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">16</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="dv">16</span><span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="fu">Sqrt</span>(<span class="dv">16</span>)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Das ist ein Kommentar.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="exr-equation" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.2</strong></span> Weise einer neuen Variable <code>x</code> den Wert <span class="math inline">\(4\)</span> zu. Weise dann einer neuen Variable <code>x2</code> den folgenden Wert zu:</p>
<p><span class="math display">\[
\sqrt{3x^2 + \log\left(\frac{1}{e^x}\right) + 5}
\]</span></p>
<p>Überlege was folgende Zeilen ausgeben und führe diese dann aus, um das Ergebnis zu überprüfen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>x</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>x2</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>x <span class="sc">+</span> x2</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>x.Produkt <span class="ot">&lt;-</span> x <span class="sc">*</span> x2</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>x.Produkt</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>x.Produkt <span class="ot">&lt;-</span> x.Produkt <span class="sc">*</span> x</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(x)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="exr-strings" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.3</strong></span> Kopiere den folgenden Code. Welche Ausgabe bewirkt der Code?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>Zahl <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>keine.Zahl <span class="ot">&lt;-</span> <span class="st">"10"</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>Zahl <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>keine.Zahl <span class="sc">+</span> <span class="dv">1</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="listen-und-vektoren" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="listen-und-vektoren"><span class="header-section-number">1.5.2</span> Listen und Vektoren</h3>
<div id="exr-lists" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.4</strong></span> Erzeuge folgende Vektoren:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5 6 7 8 9</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 10  9  8  7  6  5  4  3  2  1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.10 -0.08 -0.06 -0.04 -0.02  0.00</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10000 12500 15000 17500 20000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -3 -2 -1  0  1  2 -3 -2 -1  0  1  2 -3 -2 -1  0  1  2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  5.0  6.0  7.0  8.0  9.0 10.0 10.1 10.2 10.3 10.4 10.5</code></pre>
</div>
</div>
</div>
<div id="exr-vectorcalc" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.5</strong></span> Gegeben sind die Vektoren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fl">0.1</span>, <span class="at">to=</span><span class="fl">0.5</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Erkläre, was folgende Ausdrücke ergeben und überprüfe das Ergebnis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">+</span> y </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>x <span class="sc">*</span> y</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>x <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span>y</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x <span class="sc">+</span> y)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(x<span class="sc">+</span>y)<span class="sc">/</span>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="exr-vectorindices" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.6</strong></span> Gegeben seien die beiden folgenden Vektoren:\[-2ex]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">100</span>, <span class="at">by=</span><span class="dv">2</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">:</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Schreibe die Ergebnisse folgender Ausdrücke auf und überprüfen anschließend das Ergebnis in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">3</span>]</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>y[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>)]</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&gt;</span> <span class="dv">91</span>]</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> <span class="dv">30</span>]</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>y[y<span class="sc">==</span><span class="dv">5</span> <span class="sc">|</span> y<span class="sc">&gt;</span><span class="dv">95</span> <span class="sc">|</span> y<span class="sc">&lt;</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="datensätze" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="datensätze"><span class="header-section-number">1.5.3</span> Datensätze</h3>
<p>Für die folgenden Übungen verwenden wir wieder den <code>data_ramen</code> Datensatz aus Sektion <a href="#sec-essentials" class="quarto-xref"><span>Section 1.3.2</span></a>.</p>
<p>Wende hierfür die zuvor durchgeführten Datenmanipulationen auf den Datensatz an, so dass die Spalte <code>top_ten</code> entfernt wurde und die Spalte <code>stars</code> in den Datentyp <code>&lt;dbl&gt;</code> umgewandelt wurden.</p>
<div id="exr-df1" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.7</strong></span> Finde heraus, aus welchen fünf Länder die meisten Ramen stammen. <em>Hinweis: Verwende die <code>arrange</code> Funktion in Kombination mit der <code>desc</code> Funktion um die Ergebnisse absteigend nach der Größe zu sortieren</em>.</p>
</div>
<div id="exr-df2" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.8</strong></span> Finde heraus, wie viele verschiedene Ramen sorten in Deutschland (<code>country == "Germany"</code>) verfügbar sind.</p>
</div>
</section>
<section id="grafiken" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="grafiken"><span class="header-section-number">1.5.4</span> Grafiken</h3>
<div id="exr-ggplot1" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.9</strong></span> Erkläre die Funktionen und Argumente des folgenden Code Snippets und erkläre was sich im Verlgeich zum unbearbeiteten Datensatz inhaltlich geändert hat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>data_ramen_filtered <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2"></a>  <span class="fu">filter</span>(style <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Bowl"</span>,<span class="st">"Cup"</span>,<span class="st">"Pack"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3"></a>  <span class="fu">mutate</span>(<span class="at">style =</span> <span class="fu">if_else</span>(</span>
<span id="cb62-4"><a href="#cb62-4"></a>    style<span class="sc">==</span><span class="st">"Pack"</span>,<span class="st">"Pack"</span>,<span class="st">"Container"</span></span>
<span id="cb62-5"><a href="#cb62-5"></a>    ),</span>
<span id="cb62-6"><a href="#cb62-6"></a>    <span class="at">style=</span> <span class="fu">factor</span>(style)</span>
<span id="cb62-7"><a href="#cb62-7"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="exr-ggplot2" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.10</strong></span> Beschreibe die folgende Grafik. Verlgeiche dabei auch die beiden Gruppen untereinander.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="exr-ggplot3" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 1.11</strong></span> Verwende den Datensatz <code>data_ramen_filtered</code> um die Dichte der Variable <code>stars</code> mit <code>{ggplot2}</code> darzustellen.</p>
</div>
</section>
</section>
<section id="lösungen" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="lösungen"><span class="header-section-number">1.6</span> Lösungen</h2>
<div id="sol-calc" class="proof solution">
<p><span class="proof-title"><em>Solution 1.1</em> (<a href="#exr-calc" class="quarto-xref">Aufgabe&nbsp;<span>1.1</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
</div>
<p>Mit diesen Befehlen wird die Rechnung <span class="math inline">\(2+3*4\)</span> durchgeführt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
</div>
<p>Im Vergleich zur vorherigen Aufgabe werden hier Klammern gesetzt, um zuerst <span class="math inline">\(2+3\)</span> zu berechnen, bevor das Ergebnis mit <span class="math inline">\(4\)</span> multipliziert wird.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.2</span> <span class="sc">*</span> <span class="dv">3</span> <span class="sc">-</span> <span class="fl">1.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5</code></pre>
</div>
</div>
<p>Neben ganzzahligen Werten, kann R auch Rechnungen mit Dezimalzahlen durchführen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="dv">0</span>,<span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span> <span class="sc">-</span> <span class="fl">1.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in parse(text = input): &lt;text&gt;:1:2: Unerwartete(s) ','
1: 0,
     ^</code></pre>
</div>
</div>
<p>Bei der obigen Rechnung wird ein Fehler ausgegeben, da das Dezimaltrennzeichen in R nicht <code>,</code>, sondern <code>.</code> ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span><span class="dv">3</span><span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 512</code></pre>
</div>
</div>
<p>Die obige Code Zeile führt die Rechnung <span class="math inline">\(2^{3^2} = 2^9\)</span> aus.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">2</span><span class="sc">^</span><span class="dv">3</span>)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64</code></pre>
</div>
</div>
<p>Wie zuvor wird durch Klammern bewirkt, dass die erste Potenzierung zuerst durchgeführt wird.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.718282</code></pre>
</div>
</div>
<p>Die <code>exp(x)</code> Funktion führt die Rechnung <span class="math inline">\(e^x\)</span> durch, wobei <span class="math inline">\(e\approx 2.718282\)</span> die eulersche Konstante ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fu">exp</span>(<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Die <code>log</code> Funktion berechnet den natürlichen Logarithmus. Die Rechnung <span class="math inline">\(\log\circ\exp\)</span> ist somit die Identitätsfunktion, also <span class="math inline">\(x\mapsto x\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>Die <code>sqrt(x)</code> Funktion führt die Rechnung <span class="math inline">\(\sqrt{x}\)</span> durch.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="dv">16</span><span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>Da <span class="math inline">\(\sqrt{16} = 16^{0.5} = 16^{\frac{1}{2}}\)</span> ist das Ergebnis identisch zur vorherigen Code Zelle.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sqrt</span>(<span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in Sqrt(16): konnte Funktion "Sqrt" nicht finden</code></pre>
</div>
</div>
<p>Hier wird ein Fehler ausgegeben, da R ist. Case Sensitivity führt dazu, dass bei dem Eingeben von Funktionen auch auf Groß- und Kleinschreibung geachtet werden muss.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Das ist ein Kommentar.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Kommentare in R werden durch das <code>#</code> Symbol intiiert. Kommentare werden nicht ausgewertet, so dass hinter dem <code>#</code> Symbol jegliche Folge von Zeichen stehen kann.</p>
</div>
<div id="sol-equation" class="proof solution">
<p><span class="proof-title"><em>Solution 1.2</em> (<a href="#exr-equation" class="quarto-xref">Aufgabe&nbsp;<span>1.2</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">3</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span><span class="fu">log</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">exp</span>(x))<span class="sc">+</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">+</span> x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>x.Produkt <span class="ot">&lt;-</span> x <span class="sc">*</span> x2</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>x.Produkt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>x.Produkt <span class="ot">&lt;-</span> x.Produkt <span class="sc">*</span> x</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "data"                "data_example"        "data_ramen"         
 [4] "data_ramen_filtered" "data_ramen_ratings"  "x"                  
 [7] "x.Produkt"           "x1"                  "x2"                 
[10] "x3"                  "y"                  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Durch die <code>rm</code> Funktion wird die Variable <code>x</code> entfernt und kann somit nicht mehr aufgerufen werden. Deshalb wird beim versuchten Aufruf in der folgenden Zeile eine Fehlermeldung ausgegeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error: Objekt 'x' nicht gefunden</code></pre>
</div>
</div>
</div>
<div id="sol-strings" class="proof solution">
<p><span class="proof-title"><em>Solution 1.3</em> (<a href="#exr-strings" class="quarto-xref">Aufgabe&nbsp;<span>1.3</span></a>). </span>Die Variable <code>keine.Zahl</code> ist vom Datentyp <code>&lt;char&gt;</code> und kann somit nicht ohne weiteres wie ein tatsächlicher Zahlenwert gehandhabt werden. Das führt dazu, dass in der folgende Code Zelle eine Fehlermeldung ausgegeben wird.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>Zahl <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>keine.Zahl <span class="ot">&lt;-</span> <span class="st">"10"</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>Zahl <span class="sc">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>keine.Zahl <span class="sc">+</span> <span class="dv">1</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in keine.Zahl + 1: nicht-numerisches Argument für binären Operator</code></pre>
</div>
</div>
</div>
<div id="sol-lists" class="proof solution">
<p><span class="proof-title"><em>Solution 1.4</em> (<a href="#exr-lists" class="quarto-xref">Aufgabe&nbsp;<span>1.4</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span><span class="sc">:</span><span class="dv">9</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5 6 7 8 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span><span class="sc">:</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 10  9  8  7  6  5  4  3  2  1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from=</span><span class="sc">-</span><span class="fl">0.1</span>, <span class="at">to=</span><span class="dv">0</span>, <span class="at">by=</span><span class="fl">0.02</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.10 -0.08 -0.06 -0.04 -0.02  0.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">10000</span>, <span class="at">to=</span><span class="dv">20000</span>, <span class="at">length.out=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10000 12500 15000 17500 20000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(<span class="sc">-</span><span class="dv">3</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -3 -2 -1  0  1  2 -3 -2 -1  0  1  2 -3 -2 -1  0  1  2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">seq</span>(<span class="at">from=</span><span class="fl">10.1</span>, <span class="at">by=</span>.<span class="dv">1</span>, <span class="at">to=</span><span class="fl">10.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  5.0  6.0  7.0  8.0  9.0 10.0 10.1 10.2 10.3 10.4 10.5</code></pre>
</div>
</div>
</div>
<div id="sol-vectorcalc" class="proof solution">
<p><span class="proof-title"><em>Solution 1.5</em> (<a href="#exr-vectorcalc" class="quarto-xref">Aufgabe&nbsp;<span>1.5</span></a>). </span>Gegeben sind die Vektoren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fl">0.1</span>, <span class="at">to=</span><span class="fl">0.5</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Da die Objeke <code>x</code> und <code>y</code> nicht die selbe Länge besitzen, werden in der folgenden Zelle die Einträge des kürzeren Vektors bis zur Länge des längeren Vektors wiederholt. Anschließend werden die einzelnen Einträge komponentenweise addiert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">+</span> y </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in x + y: Länge des längeren Objektes
     ist kein Vielfaches der Länge des kürzeren Objektes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.1 3.2 2.3 4.4 3.5</code></pre>
</div>
</div>
<p>In der folgenden Code Zelle werden die Listeneinträge von <code>x</code> analog erweitert und dann komponentenweise mit den Einträgen von <code>y</code> multipliziert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">*</span> y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in x * y: Länge des längeren Objektes
     ist kein Vielfaches der Länge des kürzeren Objektes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4 0.6 0.6 1.6 1.5</code></pre>
</div>
</div>
<p>Durch den <code>^</code> Operator werden zuerst alle Elemente der Liste <code>x</code> potenziert und anschlißend mit dem Wert <code>1</code> addiert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>x<span class="sc">^</span><span class="dv">3</span> <span class="sc">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 65 28  9</code></pre>
</div>
</div>
<p>Analog wie in den vorherigen Teilaufgaben werden die konstanten Faktoren zuerst komponentenweise multipliziert, bevor die Liste <code>x</code> erweitert werden und von <code>3*y</code> komponentenweise abgezogen werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>x <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in 2 * x - 3 * y: Länge des längeren Objektes
     ist kein Vielfaches der Länge des kürzeren Objektes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.7 5.4 3.1 6.8 4.5</code></pre>
</div>
</div>
<p>Die Länge der Liste <code>x+y</code> is gegeben durch die Länge des längsten Elements in der Summe. Also durch die Länge von <code>y</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x <span class="sc">+</span> y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in x + y: Länge des längeren Objektes
     ist kein Vielfaches der Länge des kürzeren Objektes</code></pre>
</div>
</div>
<p>Analog wie in den vorherigen Teilaufgaben wird die Summe von <code>x</code> und <code>y</code> berechnet, dann die Summe der einzelnen komponenten und zum Schluss wird die Summe durch <code>n</code> geteilt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(x<span class="sc">+</span>y)<span class="sc">/</span>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in x + y: Länge des längeren Objektes
     ist kein Vielfaches der Länge des kürzeren Objektes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.5</code></pre>
</div>
</div>
</div>
<div id="sol-vectorindices" class="proof solution">
<p><span class="proof-title"><em>Solution 1.6</em> (<a href="#exr-vectorindices" class="quarto-xref">Aufgabe&nbsp;<span>1.6</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">100</span>, <span class="at">by=</span><span class="dv">2</span>)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">:</span><span class="dv">1</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>y[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">10</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100  98  91</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 2 4 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&gt;</span> <span class="dv">91</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  92  94  96  98 100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> <span class="dv">30</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22 24 26 28 30</code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>y[y<span class="sc">==</span><span class="dv">5</span> <span class="sc">|</span> y<span class="sc">&gt;</span><span class="dv">95</span> <span class="sc">|</span> y<span class="sc">&lt;</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100  99  98  97  96   5   2   1</code></pre>
</div>
</div>
</div>
<div id="sol-df1" class="proof solution">
<p><span class="proof-title"><em>Solution 1.7</em> (<a href="#exr-df1" class="quarto-xref">Aufgabe&nbsp;<span>1.7</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  country         n
  &lt;chr&gt;       &lt;int&gt;
1 Japan         352
2 USA           323
3 South Korea   307
4 Taiwan        224
5 Thailand      191</code></pre>
</div>
</div>
</div>
<div id="sol-df2" class="proof solution">
<p><span class="proof-title"><em>Solution 1.8</em> (<a href="#exr-df2" class="quarto-xref">Aufgabe&nbsp;<span>1.8</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country<span class="sc">==</span><span class="st">"Germany"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27</code></pre>
</div>
</div>
</div>
<div id="sol-ggplot1" class="proof solution">
<p><span class="proof-title"><em>Solution 1.9</em> (<a href="#exr-ggplot1" class="quarto-xref">Aufgabe&nbsp;<span>1.9</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1"></a>data_ramen_filtered <span class="ot">&lt;-</span> data_ramen <span class="sc">%&gt;%</span></span>
<span id="cb149-2"><a href="#cb149-2"></a>  <span class="fu">filter</span>(style <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Bowl"</span>,<span class="st">"Cup"</span>,<span class="st">"Pack"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb149-3"><a href="#cb149-3"></a>  <span class="fu">mutate</span>(<span class="at">style =</span> <span class="fu">if_else</span>(</span>
<span id="cb149-4"><a href="#cb149-4"></a>    style<span class="sc">==</span><span class="st">"Pack"</span>,<span class="st">"Pack"</span>,<span class="st">"Container"</span></span>
<span id="cb149-5"><a href="#cb149-5"></a>    ),</span>
<span id="cb149-6"><a href="#cb149-6"></a>    <span class="at">style=</span> <span class="fu">factor</span>(style)</span>
<span id="cb149-7"><a href="#cb149-7"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>In der ersten Zeile wird ein neuer Datenesatz <code>data_ramen_filtered</code> erzeugt indem der Datensatz <code>data_ramen</code> modifiziert wird.</li>
<li>In der zweiten Zeile wird die <code>filter</code> Funktion auf den Datensatz <code>data_ramen</code> angewandt. Der <code>%in%</code> Operator prüft hierbei, ob in der Spalte <code>style</code> die Werte <code>"Bowl","Cup","Pack"</code> vorhanden sind und geben den Wert <code>TRUE</code> oder <code>FALSE</code> zurück. D.h., es werden alle Einträge selektiert, welche den Style <code>"Bowl","Cup"</code>, oder <code>"Pack"</code> enthalten.</li>
<li>In der dritten Zeile wird die <code>mutate</code> Funktion auf die Variable <code>style</code> angewendet.</li>
<li>Die Transformation erfolgt hierbei in der vierten und fünften Zeile durch die <code>if_else</code> Funktion, welche die Kondition <code>style=="Pack"</code> überprüft. Falls der Style eines Eintrags <code>"Pack"</code> ist, so wird diesem wieder der Wert <code>"Pack"</code> zugeschrieben. Falls allerdings der Style <code>"Cup"</code> oder <code>"Bowl"</code> beträgt, so wird der Wert mit <code>"Container"</code> überschrieben.</li>
<li>In der sechsten Zeile wird wird die Variable <code>"Style"</code> dann in eine Faktorvariable umgewandelt.</li>
</ol>
</div>
<div id="sol-ggplot2" class="proof solution">
<p><span class="proof-title"><em>Solution 1.10</em> (<a href="#exr-ggplot2" class="quarto-xref">Aufgabe&nbsp;<span>1.10</span></a>). </span>Beschreibe die folgende Grafik. Verlgeiche dabei auch die beiden Gruppen untereinander.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die Grafik zeigt zwei Boxplots für die Variable <code>star</code>. Auf der linken Seite wird ein Boxplot für alle Einträge welche den Style <code>"Container"</code> besitzen angezeigt und auf der rechten Seite ein Boxplot für alle Einträge welche den Style <code>"Pack"</code> besitzen. Es lässt sich an den Boxplots ablesen, dass die beiden Dtyles einen ähnlichen Median bezüglich der Bewertung besitzen. Allerdings ist das <span class="math inline">\(25\%\)</span> Quartil beim Style <code>"Container"</code> etwas kleiner als beim Style <code>"Pack"</code>. Beim Style <code>"Pack"</code> werden auf der anderen Seite aber mehr Ausreißer nach Unten abgebildet.</p>
</div>
<div id="sol-ggplot3" class="proof solution">
<p><span class="proof-title"><em>Solution 1.11</em> (<a href="#exr-ggplot3" class="quarto-xref">Aufgabe&nbsp;<span>1.11</span></a>). </span>Verwende den Datensatz <code>data_ramen_filtered</code> um die Dichte der Variable <code>stars</code> mit <code>{ggplot2}</code> darzustellen. <em>Hinweis: Die Dichte einer Variable kann mithilfe der Funktion <code>geom_density</code> dargestellt werden.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>data_ramen_filtered <span class="sc">%&gt;%</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>stars))<span class="sc">+</span></span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill=</span><span class="st">"#69b3a2"</span>, <span class="at">color=</span><span class="st">"#69b3a2"</span>)<span class="sc">+</span></span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01_Einfuehrung_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<!--
## Session Info

Die Funktion `sessionInfo()` erfasst detaillierte Informationen über die aktuelle R-Sitzung, einschließlich der Version von R und der geladenen Pakete.
Dies ist nützlich, um die Reproduzierbarkeit von Analysen und die Fehlersuche im Code sicherzustellen, da es eine Momentaufnahme der Umgebung liefert, in der der Code ausgeführt wurde.





::: {.cell}

```{.r .cell-code}
sessionInfo()
```

::: {.cell-output .cell-output-stdout}

```
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4    
 [5] purrr_1.0.2     readr_2.1.5     tidyr_1.3.1     tibble_3.2.1   
 [9] ggplot2_3.5.1   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] compiler_4.2.3    pillar_1.9.0      tools_4.2.3       digest_0.6.35    
 [5] timechange_0.3.0  jsonlite_1.8.8    evaluate_1.0.1    lifecycle_1.0.4  
 [9] gtable_0.3.5      pkgconfig_2.0.3   rlang_1.1.3       cli_3.6.2        
[13] rstudioapi_0.17.1 yaml_2.3.8        xfun_0.43         fastmap_1.1.1    
[17] janitor_2.2.0     withr_3.0.2       knitr_1.43        generics_0.1.3   
[21] vctrs_0.6.5       htmlwidgets_1.6.4 hms_1.1.3         grid_4.2.3       
[25] tidyselect_1.2.1  snakecase_0.11.1  glue_1.6.2        R6_2.5.1         
[29] fansi_1.0.4       rmarkdown_2.28    farver_2.1.1      tzdb_0.4.0       
[33] magrittr_2.0.3    scales_1.3.0      htmltools_0.5.8.1 colorspace_2.1-0 
[37] labeling_0.4.3    utf8_1.2.3        stringi_1.8.3     munsell_0.5.1    
```


:::
:::




-->


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Vorwort">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Vorwort</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02_Lineare_Regression.html" class="pagination-link" aria-label="Lineare Regression">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineare Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>