<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Klassifikation – Data Mining Übungsmaterial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_Neuronale_Netze.html" rel="prev">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-K9CJ1KN8ZH"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K9CJ1KN8ZH', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06_Klassifikation.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Klassifikation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Mining Übungsmaterial</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Einfuehrung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">(Kurz)Einführung in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Lineare_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineare Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Wichtige_Konzepte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Weiterführende Konzepte des Dataminings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Regressions_Baeume.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regressionsbäume</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Neuronale_Netze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Neuronale Netze</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Klassifikation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Klassifikation</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro_class" id="toc-sec-intro_class" class="nav-link active" data-scroll-target="#sec-intro_class"><span class="header-section-number">6.1</span> Einführung</a></li>
  <li><a href="#evaluation-eines-binären-klassifikationsmodells" id="toc-evaluation-eines-binären-klassifikationsmodells" class="nav-link" data-scroll-target="#evaluation-eines-binären-klassifikationsmodells"><span class="header-section-number">6.2</span> Evaluation eines binären Klassifikationsmodells</a>
  <ul>
  <li><a href="#sec-confmat" id="toc-sec-confmat" class="nav-link" data-scroll-target="#sec-confmat"><span class="header-section-number">6.2.1</span> Confusionmatrix</a></li>
  <li><a href="#roc-kurve" id="toc-roc-kurve" class="nav-link" data-scroll-target="#roc-kurve"><span class="header-section-number">6.2.2</span> ROC-Kurve</a></li>
  </ul></li>
  <li><a href="#die-logistische-regression" id="toc-die-logistische-regression" class="nav-link" data-scroll-target="#die-logistische-regression"><span class="header-section-number">6.3</span> Die Logistische Regression</a>
  <ul>
  <li><a href="#modellgleichung" id="toc-modellgleichung" class="nav-link" data-scroll-target="#modellgleichung"><span class="header-section-number">6.3.1</span> Modellgleichung</a></li>
  <li><a href="#sec-lrinterp" id="toc-sec-lrinterp" class="nav-link" data-scroll-target="#sec-lrinterp"><span class="header-section-number">6.3.2</span> Interpretation der Koeffizienten</a></li>
  <li><a href="#statistische-signifikanz" id="toc-statistische-signifikanz" class="nav-link" data-scroll-target="#statistische-signifikanz"><span class="header-section-number">6.3.3</span> Statistische Signifikanz</a></li>
  </ul></li>
  <li><a href="#klassifikationsbäume" id="toc-klassifikationsbäume" class="nav-link" data-scroll-target="#klassifikationsbäume"><span class="header-section-number">6.4</span> Klassifikationsbäume</a></li>
  <li><a href="#neuronale-netze" id="toc-neuronale-netze" class="nav-link" data-scroll-target="#neuronale-netze"><span class="header-section-number">6.5</span> Neuronale Netze</a></li>
  <li><a href="#klassifizierung-in-r" id="toc-klassifizierung-in-r" class="nav-link" data-scroll-target="#klassifizierung-in-r"><span class="header-section-number">6.6</span> Klassifizierung in R</a>
  <ul>
  <li><a href="#sec-logreg" id="toc-sec-logreg" class="nav-link" data-scroll-target="#sec-logreg"><span class="header-section-number">6.6.1</span> Logistische Regression</a></li>
  <li><a href="#klassifikationsbäume-1" id="toc-klassifikationsbäume-1" class="nav-link" data-scroll-target="#klassifikationsbäume-1"><span class="header-section-number">6.6.2</span> Klassifikationsbäume</a></li>
  <li><a href="#neuronale-netze-1" id="toc-neuronale-netze-1" class="nav-link" data-scroll-target="#neuronale-netze-1"><span class="header-section-number">6.6.3</span> Neuronale Netze</a></li>
  </ul></li>
  <li><a href="#übungsaufgaben" id="toc-übungsaufgaben" class="nav-link" data-scroll-target="#übungsaufgaben"><span class="header-section-number">6.7</span> Übungsaufgaben</a></li>
  <li><a href="#lösungen" id="toc-lösungen" class="nav-link" data-scroll-target="#lösungen"><span class="header-section-number">6.8</span> Lösungen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Klassifikation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Neben der Regression beschäftigen wir uns im Zuge des Supervised-Learnings auch mit der Klassifikation. Im Verlgeich zu Regressionsaufgaben ist die Zielvariable bei der Klassifikation nicht mehr metrisch, sondern nominal. Es gibt für die Zielvariablen also keine bestimmte Ordnung mehr und zusätzlich gehen wir auch davon aus, dass die Anzahl der Ausprägungen der Zielvariable endlich ist.</p>
<section id="sec-intro_class" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-intro_class"><span class="header-section-number">6.1</span> Einführung</h2>
<p>In dieser Verasntaltung setzen wir uns vor allem mit der binären Klassifikation auseinander. Die Zielvariable <span class="math inline">\(Y\)</span> nimmt also nur zwei Werte an. Normalerweise kodiert man diese Werte mit <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span>, so dass sich <span class="math inline">\(Y\)</span> darstellen lässt als Vektor <span class="math inline">\(Y\in\{0,1\}^K\)</span>. Wir sind nun daran interessiert für einen Datenpunkt <span class="math inline">\(x\in\mathbb{R}^{J}\)</span> die Wahrscheinlichkeit <span class="math display">\[\begin{equation}
  \mathbb{P}(Y=1|X=x)
\end{equation}\]</span> zu schätzen. Falls die geschätzte Wahrscheinlichkeit <span class="math inline">\(\hat{p}\)</span> größer als ein bestimmter, vordefinierter Schwellenwert <span class="math inline">\(q\in(0,1)\)</span> ist, dann weisen wir das Sample der Klasse <span class="math inline">\(1\)</span> zu. Intuitiv macht hierbei der Wert <span class="math inline">\(q=0.5\)</span> Sinn, da wir uns bei einer Wahrscheinlichkeit <span class="math inline">\(p&gt;0.5\)</span> sicherer sind, dass der Datenpunkt zur Klasse <span class="math inline">\(1\)</span> als zur Klasse <span class="math inline">\(0\)</span> gehört.</p>
</section>
<section id="evaluation-eines-binären-klassifikationsmodells" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="evaluation-eines-binären-klassifikationsmodells"><span class="header-section-number">6.2</span> Evaluation eines binären Klassifikationsmodells</h2>
<p>Da eine Evaluation mithilfe von Metriken wie <span class="math inline">\(\text{RMSE}\)</span> und <span class="math inline">\(R^2\)</span> bei der binären Klassifikation wenig Sinn ergeben, wollen wir in diesem Abschnitt verschiedene alternativen Metriken betrachten.</p>
<section id="sec-confmat" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-confmat"><span class="header-section-number">6.2.1</span> Confusionmatrix</h3>
<p>Als Grundlage für die Metriken welche wir im Folgenden betrachten wollen ist die sogenannte <em>Confusion Matrix</em>. Diese Kreuztabelle gibt an, wie viele Datenpunkte korrekt bzw. inkorrekt klassifiziert wurden. Hierbei wird insbesondere zwischen den Klassen <em>Negativ</em> und <em>Positiv</em> Unterschieden. Im vorherigen Abschnitt wurden die Klassen mit <span class="math inline">\(1\)</span> und <span class="math inline">\(0\)</span> enkodiert. Meistens steht <span class="math inline">\(1\)</span> im Kontext der Confusion Matrix für <strong>Positive</strong> und <span class="math inline">\(0\)</span> für <strong>Negative</strong>.</p>
<div id="fig-cm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="50%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pictures/CF.svg" id="fig-cm" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1
</figcaption>
</figure>
</div>
<p>Die Felder der Confusion Matrix können wir am besten anhand eines Beispiels illustrieren.</p>
<div id="exm-cf" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 6.1</strong></span> Ein Forscherteam des Universitätsklinikums hat einen Test für das Feststellen einer seltenen Herzkrankheit entwickelt. Falls die Ärzte diese Herzkrankheit korrekt feststellen, kann diese durch einen operativen Eingriff geheilt werden. Die Wahrscheinlichkeit eines erfolgreichen Eingriffs ist hierbei größer als die Wahrscheinlichkeit, dass eine kranke Person den Krankheitsverlauf überlebt. Ein positives Testergebnis wird mit <span class="math inline">\(1\)</span> bzw. <strong>Predicted Positive</strong> enkodiert und ein negatives Ergebnis mit <span class="math inline">\(0\)</span> bzw. <strong>Predicted Negative</strong>. Nun gibt es folgende Möglichkeiten:</p>
<ol type="1">
<li>Der Test ist Positiv und die untersuchte Person hat die Krankheit. Dann spricht man von <strong>True Positive</strong>.</li>
<li>Der Test ist Positiv und die untersuchte Person hat die Krankheit nicht. Dann spricht man von <strong>False Positive</strong>.</li>
<li>Der Test ist Negativ und die untersuchte Person hat die Krankheit nicht. Dann spricht man von <strong>True Negative</strong>.</li>
<li>Der Test ist Negativ und die untersuchte Person hat die Krankheit. Dann spricht man von <strong>False Negative</strong>.</li>
</ol>
</div>
<p>Neben einer korrekten Klassifikation (TP und TN) sollten wir uns besonders mit den beiden fehlerhaften Klassifikationsszenarien auseinandersetzen. In <a href="#exm-cf" class="quarto-xref">Example&nbsp;<span>6.1</span></a> ist eine fälschlicherweise als Negativ klassifizierte Person (FN) also ein Patient oder eine Patientin, welche die Herzkrankheit besizt, aber nicht diagnostiziert wird. Diese Art von Fehler ist im Beispiel besonders gravierend, da die Person eine höhere Überlebenswahrscheinlichkeit durch den operativen Eingriff besitzt. Falls eine Person fälschlicherweise als Positiv klassifiziert wird (FP), dann bedeutet das, dass der Test positiv ausfällt, obwohl die Person nicht an der Herzkrankheit erkrankt ist. Unter gewöhnlichen Umständen wäre eine solche Fehlklassifikation nicht ganz so gravierend, da die Person schließlich nicht an der seltenen Krankheit erkrankt ist. Falls allerdings auf Basis des Testergebnisses trotzdem ein operativer Eingriff vorgenommen wird, dann setzt man den Patient oder die Patientin einem unnötigen Risiko aus.</p>
<p>Wie gut also so ein Test tatsächlich funktioniert, sollte man also nicht nur an der absoluten oder relativen Anzahl der korrekt klassifizierten Datenpunkte festmachen, sondern auch daran, wie hoch die entsprechenden Fehlerquoten sind.</p>
<p>Präziser lässt sich diese Aussage mit folgenden Kennzahlen ausdrücken:</p>
<ul>
<li>Accuracy: <span class="math display">\[\begin{equation*}
  \text{Accuracy} = \frac{TP+TN}{TP+TN+FP+FN}
\end{equation*}\]</span> Die Accuracy misst den relativen Anteil der korrekt klassifizierten Datenpunkte an der Gesamtanzahl der Datenpunkte. Sie beschreibt die Wahrscheinlichkeit für ein korrektes Testergebnis.</li>
<li>Sensitivität: <span class="math display">\[\begin{equation*}
  \text{Sensitivity} = \frac{TP}{TP+FN}
\end{equation*}\]</span> Die Sensitivität misst den relativen Anteil der als korrekterweise positiv klassifizierten Datenpunkte an der Gesamtanzahl der positiven Datenpunkte. Sie beschreibt die bedingte Wahrscheinlichkeit, dass ein positives Ergebnis vorhergesagt wird unter der Annahme, dass das Ergebnis tatsächlich positiv ist.</li>
<li>Spezifizität: <span class="math display">\[\begin{equation*}
  \text{Specificity} = \frac{TN}{TN+FP}
\end{equation*}\]</span> Die Spezifizität ist das Gegenstück zur Sensititivität. Sie misst den relativen Anteil der als korrekterweise negativ klassifizierten Datenpunkte an der Gesamtanzahl der negativen Datenpunkte. Spezifizität kann auch als die bedingte Wahrscheinlichkeit interpretiert werden, dass ein negatives Ergebnis vorhergesagt wird, unter der Annahme, dass das Ergebnis tatsächlich negativ ist.</li>
<li>Präzision: <span class="math display">\[\begin{equation*}
  \text{Precision} = \frac{TP}{TP+FP}
\end{equation*}\]</span> Die Präzision misst den relativen Anteil der korrekterweise als positiv klassifizierten Datenpunkte an der Gesamtzahl der als positiv klassifizierten Datenpunkte. Besonders bei unbalancierten Datensätzen<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> ist die Präzision eine wichtige Metrik, da die Accuracy bei unbalacierten Datensätzen zu Trugschlüssen führen kann.</li>
</ul>
</section>
<section id="roc-kurve" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="roc-kurve"><span class="header-section-number">6.2.2</span> ROC-Kurve</h3>
<p>In <a href="#sec-intro_class" class="quarto-xref"><span>Section 6.1</span></a> haben wir kurz den Entscheidungsprozess bei einer Klassifikation in Abhängigkeit des Schwellenwerts <span class="math inline">\(q\)</span> eingeführt. Da der Schwellenwert <span class="math inline">\(q\)</span> allerdings stark die Confusion Matrix beeinflussen kann, sollte man sich verschiedene Schwellenwerte in Abhängigkeit ausgewählter Metriken betrachten. Eine dieser Gegenüberstellungen ist durch die sogenannte <em>Receiver-Operator Characteristic</em> Kurve gegeben. Diese zeigt auf der <span class="math inline">\(x\)</span>-Achhse die False-Positive Rate (<span class="math inline">\(1-\text{specificity}\)</span>) und auf der <span class="math inline">\(y\)</span>-Achse die Sensitivität an. Der Kurve ergibt sich dann durch das Variieren des Schwellenwerts <span class="math inline">\(q\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die ROC-Kurve ist monoton steigend, d.h. je größer der Schwellenwert <span class="math inline">\(q\)</span> ist, desto größer wird die False Positive Rate (<span class="math inline">\(1-\text{specificity}\)</span>). Gleichzeitig steigt aber auch die Sensitivität, also der relative Anteil der als korrekterweise positiv klassifizierten Datenpunkte an der Gesamtanzahl der positiven Datenpunkte. Der optimale Threshold ist dann durch jenen Punkt gegeben, welcher am am nähsten zum Punkt <span class="math inline">\((1,0)\)</span> ist. Ein Entscheidungsschwellenwert von <span class="math inline">\(0.5\)</span> ist also nicht zwingende der optimale Schwellenwert für eine Entscheidung, wenn das Ziel ist gleichzeitig die Sensitivität zu maximieren und die False Positive Rate zu minimieren.</p>
<p>Die Winkelhalbierende beschreibt den Fall, dass die Sensitivität gleich der False Positive Rate ist. Falls diese beiden Metriken gleich sind, dann kann das unterliegende Modell nicht zwischen True Positives und False Positives unterscheiden. Dieser Fall wird dann auch gerne als <em>Münzwurf</em> beschrieben, da die Wahrscheinlichkeit für eine korrekte, bzw. falsche Klassifizierung <span class="math inline">\(50\%\)</span> beträgt.</p>
<p>Die ROC-Kurve kann allerdings auch irreführend sein, weshalb man neben dieser Metrik auch noch andere Metriken betrachten sollte. Besonders, falls die Klassen unbalanciert sind kann die ROC-Kurve irreführend sein, da sie keine Informationen bezüglich der Präzision des Modells enthält.</p>
<p>Neben dem Ablesen der Sensitivität und False Positive Rate an der Kurve selbst können wir auch die Fläche unter der Kurve berechnen. Die sogenannte Area under the Receiver Operator Characteristic (AUROC) nimmt dabei Werte zwischen <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> an, wobei <span class="math inline">\(1\)</span> einem perfekten Modell entspricht und <span class="math inline">\(0\)</span> einem Modell, welches alle Vorhersagen falsch trifft.</p>
<!-- Warum ist AAUCROC= 0 nicht schlimm, sondern ROCAUC = 0.5? -->
</section>
</section>
<section id="die-logistische-regression" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="die-logistische-regression"><span class="header-section-number">6.3</span> Die Logistische Regression</h2>
<p>Als Erweiterung der linearen Regression erlaubt es uns die logisitische Regression ebenso eine einfache Parametrisierung der geschätzten Wahrscheinlichkeit <span class="math inline">\(\hat{p}\)</span>. Betrachten wir zuerst den Fall, dass unser Datensatz aus lediglich einer unabhängigen Variable besteht. Im Falle der linearen Regression schätzen wir dann die Parameter <span class="math inline">\(b_0\)</span> und <span class="math inline">\(b_1\)</span> der Gleichung (vgl. <a href="02_Lineare_Regression.html#eq-elr" class="quarto-xref">Gleichung&nbsp;<span>2.1</span></a>)</p>
<p><span class="math display">\[\begin{equation*}
Y = b_0 + b_1 X + \varepsilon
\end{equation*}\]</span></p>
<section id="modellgleichung" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="modellgleichung"><span class="header-section-number">6.3.1</span> Modellgleichung</h3>
<p>Wir können diese Modellgleichung dann mithilfe der logistischen Funktion <span class="math display">\[\begin{equation*}
  \sigma(x) = \frac{1}{1+\exp(-x)} \in (0,1) , x\in\mathbb{R}
\end{equation*}\]</span> so transformieren, dass die Werte der Regressionsgleichung zwischen <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> liegen. Die Werte dieser transformierten Regressionsgleichung können dann als Wahrscheinlichkeiten interpretiert werden. Wir erhalten also nach dem Schätzen der Parameter die Modellgleichung</p>
<p><span class="math display">\[\begin{equation*}
  \widehat{\mathbb{P}(Y=1|X=x)} = \frac{1}{1+\exp\left(-(b_0+b_1x)\right)}
\end{equation*}\]</span></p>
<p>Diese Schätzgleichung lässt sich dann analog zum MLR Modell erweitern zu</p>
<p><span class="math display">\[\begin{equation*}
  \widehat{\mathbb{P}(Y=1|X=x_k)} = \frac{1}{1+\exp\left(-(b_0+\sum_{j=1}^Jb_jx_{k,j})\right)}
\end{equation*}\]</span></p>
<p>Die Parameter dieser Schätzgleichung werden mithilfe der Maximum Likelihood Methode durchgeführt, da eine analytische Lösung wie für die Parameter des MLR nur schwer zu berechnen ist.</p>
<div id="exm-logistic_reg" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 6.2</strong></span> Betrachten wir folgendes Beispiel:</p>
<p>Die Schätzgleichung einer einfachen linearen Regression sei durch <span class="math display">\[\begin{equation*}
  y = \hat{b}_0+\hat{b}_1 x  = 4x + 1
\end{equation*}\]</span></p>
<p>gegeben:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dann eignet sich diese Funktion nicht, um eine Wahrscheinlichkeit vorherzusagen, da die Funktion für <span class="math inline">\(x &lt; -0.25\)</span> negative Werte annimmt und für <span class="math inline">\(x&gt;0\)</span> Werte annimmt, welche größer als <span class="math inline">\(1\)</span> sind.</p>
<p>Durch eine Transformation dieser Schätzgleichung zu einer logistischen Schätzgleichung der Form</p>
<p><span class="math display">\[\begin{equation*}
\widehat{\mathbb{P}(y=1|x)} = \frac{1}{1+\exp(-(\hat{b}_0 + \hat{b}_1 x))} =\frac{1}{1+\exp(-(4x + 1))}
\end{equation*}\]</span></p>
<p>erreichen wir, dass die Funktionswerte nur noch im Intervall <span class="math inline">\((0,1)\)</span> liegen:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Je größer also die Werte für <span class="math inline">\(x\)</span> sind, desto höher ist die Wahrscheinlichkeit, dass wir die Klassifikation <span class="math inline">\(y=1\)</span> annehmen.</p>
</div>
</section>
<section id="sec-lrinterp" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="sec-lrinterp"><span class="header-section-number">6.3.2</span> Interpretation der Koeffizienten</h3>
<p>Im Vergleich zur multiplen Linearen Regression lassen sich die Koeffizienten des logistischen Modells nicht mehr direkt interpretieren. Auch die Überprüfung der Signifikanz einzelner Variablen ist nicht mehr mithilfe des <span class="math inline">\(t\)</span> Test umsetzbar.</p>
<p>Grundlegend können wir allerdings folgende Aussagen treffen:f Das Vorzeichen eines geschätzeten Parameters gibt Auskunft darüber, ob die geschätzte Wahrscheinlichkeit beim Erhöhen der Variable (um eine Einheit) steigt oder sinkt.</p>
<ul>
<li>Falls <span class="math inline">\(b_j&gt;0,\: j\in\{1,...,J\}\)</span> so steigt die geschätzte Wahrscheinlichkeit <span class="math inline">\(\widehat{\mathbb{P}(Y=1|X)}\)</span>.</li>
<li>Falls <span class="math inline">\(b_j&lt;0,\: j\in\{1,...,J\}\)</span>, dann sinkt die geschätzte Wahrscheinlichkeit <span class="math inline">\(\widehat{\mathbb{P}(Y=1|X)}\)</span>.</li>
</ul>
<p>Um den Einfluss einer Variable zu quantifizieren, betrachten wir die sogenannten <em>Odds</em>. Die Odds sind definiert als <span class="math display">\[\begin{equation}\label{eq:odds}
\mathrm{Odds} = \frac{\mathbb{P}(Y=1|X=x)}{\mathbb{P}(Y=0|X=x)} = \exp(b_0+\sum_{j=1}^Jb_jx_j)
\end{equation}\]</span> Die Odds können Werte im Intervall <span class="math inline">\((0,\infty)\)</span> annehmen. Sie können interpretiert werden als die Chance dessen, dass ein Event eintritt (<span class="math inline">\(y=1\)</span>) gegenüber dem nichteintreten des Events <span class="math inline">\((y=0)\)</span>.</p>
<div id="exm-odds" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 6.3</strong></span> Bei einem Wettanbieter für Fußballwetten sind für ein Spiel der Mannschaft <span class="math inline">\(A\)</span> gegen Mannschaft <span class="math inline">\(B\)</span> die dezimalen Odds (Quoten) für einen Sieg von Mannschaft <span class="math inline">\(A\)</span> mit <span class="math inline">\(1.75\)</span> und für einen Sieg von Mannschaft <span class="math inline">\(B\)</span> mit <span class="math inline">\(2.10\)</span> gegeben. Es wird angenommen, dass kein Unentschieden möglich ist. Die dezimalen Odds geben an, wie viel ein Spieler für einen eingesetzten Euro im Falle eines Gewinns zurückerhält (inklusive des Einsatzes). Die vom Wettanbieter implizierten Wahrscheinlichkeiten werden wie folgt berechnet:</p>
<ol type="1">
<li><p>Die implizierte Wahrscheinlichkeit für einen Sieg von <span class="math inline">\(A\)</span> ist:</p>
<p><span class="math display">\[\begin{equation*}
  \mathbb{P}_{\text{impl}}(A) = \frac{1}{\text{Odds}(A)} = \frac{1}{1.75} \approx 0.5714
\end{equation*}\]</span></p></li>
<li><p>Die implizierte Wahrscheinlichkeit für einen Sieg von <span class="math inline">\(B\)</span> ist:</p>
<p><span class="math display">\[\begin{equation*}
  \mathbb{P}_{\text{impl}}(B) = \frac{1}{\text{Odds}(B)} = \frac{1}{2.10} \approx 0.4762
\end{equation*}\]</span></p></li>
</ol>
<p>Die Summe der implizierten Wahrscheinlichkeiten ist: <span class="math display">\[\begin{equation*}
  \mathbb{P}_{\text{impl}}(A) + \mathbb{P}_{\text{impl}}(B) \approx 0.5714 + 0.4762 = 1.0476
\end{equation*}\]</span> Diese Summe ist größer als 1, was die Wettmarge (Overround) des Anbieters widerspiegelt. Die tatsächlichen Wahrscheinlichkeiten, die der Wettanbieter zugrunde legt (nach Bereinigung der Marge), erhält man durch Normalisierung: <span class="math display">\[\begin{equation*}
  \mathbb{P}(A) = \frac{\mathbb{P}_{\text{impl}}(A)}{\mathbb{P}_{\text{impl}}(A) + \mathbb{P}_{\text{impl}}(B)} = \frac{0.5714}{1.0476} \approx 0.5455
\end{equation*}\]</span> <span class="math display">\[\begin{equation*}
  \mathbb{P}(B) = \frac{\mathbb{P}_{\text{impl}}(B)}{\mathbb{P}_{\text{impl}}(A) + \mathbb{P}_{\text{impl}}(B)} = \frac{0.4762}{1.0476} \approx 0.4545
\end{equation*}\]</span></p>
<p>Somit rechnet der Wettanbieter mit einer Wahrscheinlichkeit von ca. <span class="math inline">\(54.55\%\)</span>, dass Mannschaft <span class="math inline">\(A\)</span> gewinnt, und mit ca. <span class="math inline">\(45.45\%\)</span>, dass Mannschaft <span class="math inline">\(B\)</span> gewinnt.</p>
</div>
<p>Falls <span class="math inline">\(\mathrm{Odds}=1\)</span>, dann sind beide Events gleich wahrscheinlich, während Odds <span class="math inline">\(&gt;1\)</span> bzw. <span class="math inline">\(&lt;1\)</span> implizieren, dass die Wahrscheinlichkeit für das Eintreten des untersuchten Events <span class="math inline">\(&gt;50\%\)</span> bzw. <span class="math inline">\(&lt;50\%\)</span> ist.</p>
<p>Der Einfluss der Modellparameter auf die Odds kann ebenso interpretiert werden:</p>
<ul>
<li>Steigt eine Variable <span class="math inline">\(X_j\)</span> um eine Einheit, so erhöhen, bzw. sinken die Odds um <span class="math inline">\(\exp(b_j)\)</span>.</li>
</ul>
<p>Falls zum Beispiel <span class="math inline">\(\exp(\hat{b}_j)=2\)</span>, so verdoppeln sich die Odds beim Erhöhen der Variable <span class="math inline">\(X_j\)</span> um eine Einheit.</p>
</section>
<section id="statistische-signifikanz" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="statistische-signifikanz"><span class="header-section-number">6.3.3</span> Statistische Signifikanz</h3>
<p>Im Vergleich zur linearen Regression können bei der logistischen Regression den <span class="math inline">\(t\)</span>-Test bzw. <span class="math inline">\(F\)</span>-Test nicht auf ein geschätztes Modell anwenden.</p>
<p>Für die gschätzten Koeffizienten verwendet man den <em>Wald</em>-Test. Hierbei werden die Hypothesen <span class="math display">\[\begin{equation*}
H_0: b_j = 0\quad\text{vs.}\quad H_1:b_j\neq 0
\end{equation*}\]</span> geprüft. Die Test Statistik ist durch <span class="math inline">\(W = \frac{\hat{b_j}}{\hat{\text{sd}}(\hat{b_j})}\)</span> gegeben und zum Berechnen des <span class="math inline">\(p\)</span>-Werts verwenden wir die Standardnormalverteilung.</p>
<p>Die statistische Signifikanz des Gesamtmodells können wir zum Beispiel mithilfe des Likelihood Ratio Tests evaluieren. Das Hypothesenpaar ist durch</p>
<p><span class="math display">\[\begin{equation*}
H_0: b_j = 0\, \forall j=1,...,J\quad\text{vs.}\quad H_1:b_j\neq 0 \text{ für mind. ein } j.
\end{equation*}\]</span></p>
<p>gegeben.</p>
<p>Die Teststatistik wird durch den Term</p>
<p><span class="math display">\[\begin{equation*}
  \nu = -LL_v
\end{equation*}\]</span></p>
<p>wobei <span class="math inline">\(-LL_v\)</span> die Log-Likelihood des Vollmodells ist, also</p>
<p><span class="math display">\[\begin{equation*}
  LL_v = \sum_{k=1}^{K}\hat{y}_k\log(\widehat{\mathbb{P}(Y=y_k|X=x_k)})+(1-\hat{y}_k)\log(1-\widehat{\mathbb{P}(Y=y_k|X=x_k)})
\end{equation*}\]</span></p>
<p>Unter der Annahme, dass <span class="math inline">\(\nu\sim \chi^2_{n-k}\)</span> ist, kann dann der entsprechende <span class="math inline">\(p\)</span>-Wert berechnet werden.</p>
</section>
</section>
<section id="klassifikationsbäume" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="klassifikationsbäume"><span class="header-section-number">6.4</span> Klassifikationsbäume</h2>
<p>In <a href="04_Regressions_Baeume.html" class="quarto-xref"><span>Chapter 4</span></a> haben wir uns bereits intensiv mit Regressionsbäumen auseinandergesetzt. Der Übergang von Regressions zu klassifikationsbäumen ist letztendlich auch nicht mehr komplex! An Stelle einer Reelwertigen Zielvariable betrachten wir in den Blattknoten nun geschätzte Klassen, bzw. Klassenwahrscheinlichkeitn. Der Algorithmus zum schätzen eines Klassifikationsbaums im Verlgeich zu Regressionsbäumen ist hierbei fast unverändert. Lediglich der Improvement Wert, welcher bei Regressionsbäumen mithilfe des <span class="math inline">\(\text{MSE}\)</span> berechnet wird, muss durch eine passende Metrik im Klassifikationskontext ersetzt werden. Diese Metrik ist durch die Gini Impurity gegeben. Für einen Knoten <span class="math inline">\(K_n\)</span> ist diese definiert als <span class="math display">\[\begin{equation*}
  1-(p_1^2+p_0^2)
\end{equation*}\]</span></p>
<p>wobei <span class="math inline">\(p_1\)</span> die relative Häufigkeit der Klasse <span class="math inline">\(1\)</span> im Knoten ist und <span class="math inline">\(p_0\)</span> die relative Häufigkeit der Klasse <span class="math inline">\(0\)</span> im Knoten. Es wird dann getestet, für welches <span class="math inline">\(p_i,\: i=0,1\)</span> das entfernen zu einem größeren Impurity Index führt. D.h., falls <span class="math inline">\(p_1\geq p_0\)</span>, dann wird der Knoten als Klassifikationswert Klasse <span class="math inline">\(1\)</span> zurückgeben. Die Entscheidung bezüglich den Splittingvariablen funktioniert gleich: Teste, für welche Variable sich die größte Reduktion der Gini Impurity ergibt und verwende diese für einen weiteren Split.</p>
<p>Die Wichtigkeit der Variablen kann dann ebenso bezüglich dieses Impurity Wertes gemessen werden, so dass wir effektiv die gleiche Permutation Feature Importance Methode verwenden können.</p>
</section>
<section id="neuronale-netze" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="neuronale-netze"><span class="header-section-number">6.5</span> Neuronale Netze</h2>
<p>Ähnlich wie bei Klassifikationsbäumen müssen wir auch bei Neuronalen Netzen lediglich die Verlustfunktion anpassen, um nominale Zielvariablen zu berücksichtigen. Der Rückgabewert eines Neuronalen Netzes bei der binären Klassifikation ist dabei nicht das Klassenlabel selbst, sondern die geschätzte Wahrscheinlichkeit <span class="math inline">\(\widehat{\mathbb{P}(Y=1|X=x)}\)</span>. Die Verlustfunktion ist durch die sogenannte Binary Cross Entropy</p>
<p><span class="math display">\[\begin{equation*}
L(y,\hat{y}) -\left(y\log(\hat{y})+(1-y)\log(1-\hat{y})\right)
\end{equation*}\]</span></p>
<p>gegeben, wobei <span class="math inline">\(\hat{y} = \widehat{\mathbb{P}(Y=1|X=x)}\)</span> und <span class="math inline">\(y\)</span> das entsprechende Klassenlabel <span class="math inline">\(1\)</span> oder <span class="math inline">\(0\)</span> ist. Wichtig ist, dass die finale Aktiverungsfunktion den Output des Neuronalen Netzes also auf das Intervall <span class="math inline">\([0,1]\)</span> skaliert, damit die Verlustfunktion auch berechnet werden kann (vgl. <a href="05_Neuronale_Netze.html#exr-nnarchitecture" class="quarto-xref">Aufgabe&nbsp;<span>5.1</span></a> Teilaufgabe 4)!</p>
</section>
<section id="klassifizierung-in-r" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="klassifizierung-in-r"><span class="header-section-number">6.6</span> Klassifizierung in R</h2>
<p>In diesem Abschnitt wollen wir die verschiedenen Klassifizierungsalgorithmen und deren Evaluation in R betrachten. Als Grundlage für diese Einführung dient der <code>penguins</code> Datensatz, welchen wir auch schon in vorherigen Übungen behandelt haben. Ziel wird es sein, die Variable Geschlecht vorherzusagen, da diese im Datensatz binär mit <code>"male"</code> und `“female</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_penguin <span class="ot">&lt;-</span> palmerpenguins<span class="sc">::</span>penguins <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>year) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">factor</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">if_else</span>(sex<span class="sc">==</span><span class="st">"male"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nachdem wir den Datensatz als <code>data_penguin</code> gespeichert haben, entfernen wir alle <code>NA</code> Werte und wandeln mithilfe der <code>mutate()</code> Funktion die Variable <code>sex</code> in eine Faktor Variable um. Die Ausprägungen setzen hierbei auf <span class="math inline">\(1\)</span>, falls ein Pinguin männlich ist und <span class="math inline">\(0\)</span>, falls ein Pinguin weiblich ist.</p>
<section id="sec-logreg" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="sec-logreg"><span class="header-section-number">6.6.1</span> Logistische Regression</h3>
<p>Ein logistisches Modell können wir mithilfe der <code>logistic_reg()</code> Funktion spezifizieren. Nach dem Spezifizieren können wir dann die Modellparameter einfach wieder mithilfe der <code>fit()</code> Funktion schätzen. Als Argumente übergeben wir der <code>fit()</code> Funktion die Daten selbst und die Formel, bezüglich welcher die Parameter geschätzt werden sollen. Da wir die Variable <code>sex</code> prognostizieren wollen, verwenden wir deshalb die Formel <code>sex~.</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>log_spec <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>log_fit <span class="ot">&lt;-</span> log_spec <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> data_penguin,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">formula =</span> sex <span class="sc">~</span>.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nach dem Schätzen der Parameter können wir wieder mithilfe der <code>extract_fit_engine()</code> Funktion die Parameter extrahieren und die Modellzusammenfassung durch die <code>summary()</code> Funktion erzeugen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span> <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = sex ~ ., family = stats::binomial, data = data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-3.4128  -0.2000   0.0022   0.1441   2.8235  

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -80.376672  12.329735  -6.519 7.08e-11 ***
speciesChinstrap   -7.402697   1.662534  -4.453 8.48e-06 ***
speciesGentoo      -8.427611   2.597027  -3.245  0.00117 ** 
islandDream         0.324158   0.809135   0.401  0.68870    
islandTorgersen    -0.507858   0.855746  -0.593  0.55287    
bill_length_mm      0.614436   0.131968   4.656 3.22e-06 ***
bill_depth_mm       1.646446   0.335798   4.903 9.43e-07 ***
flipper_length_mm   0.026654   0.048307   0.552  0.58111    
body_mass_g         0.005819   0.001087   5.352 8.71e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 461.61  on 332  degrees of freedom
Residual deviance: 126.05  on 324  degrees of freedom
AIC: 144.05

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>Die Variable <code>island</code> scheintnicht statistisch signifikant zum Niveau <span class="math inline">\(\alpha = 0.1\)</span> zu sein, was auch den Erwartungen entspricht, da auf jeder Insel sowohl männliche als auch weibliche Pinguine leben. Allerdings stellt sich dann natürlich wieder die Frage, warum die Variable <code>species</code> statistisch signifikant ist! Eine mögliche Ursache wäre Multikollinearität, wobei wir das an dieser Stelle nicht weiter untersuchen wollen. Außerdem ist die Variable <code>flipper_length_mm</code> nicht statistisch signifikant zum Niveau <span class="math inline">\(\alpha = 0.1\)</span>. Ein Grund hierfür könnte sein, dass die durchschnittliche Länge der Flossen bei männlichen und weiblichen Pinguinen gleichgroß ist.</p>
<p>Um das Modell zu evaluieren, sollten wir zunächst eine Confusion Matrix erzeugen. Dafür müssen wir zunächst Vorhersagen generieren. Wir dafür die <code>augment()</code> Funktion direkt auf das <code>log_fit</code> Objekt unter Verwendung des Arguments <code>data_penguin</code> anewenden. Der Rückgabewert ist ein Tibble welches neben dem übergebenen Datensatz noch die Spalten <code>.pred_class</code>, <code>.pred_0</code> und <code>pred_1</code> enthält.</p>
<ul>
<li>Die Spalte <code>.pred_class</code> enthält die vorhergesagte Klasse ermittelt durch den Schwellenwert <span class="math inline">\(q=0.5\)</span>.</li>
<li>Die Spalte <code>.pred_0</code> enthält die geschätzte Wahrscheinlichkeit, dass der Datenpunkt zur Klasse <span class="math inline">\(0\)</span> (<code>sex = "female"</code>) gehört.</li>
<li>Die Spalte <code>.pred_1</code> enthält die geschätzte Wahrscheinlichkeit, dass der Datenpunkt zur Klasse <span class="math inline">\(1\)</span> (<code>sex = "male"</code>) gehört.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 333
Columns: 10
$ .pred_class       &lt;fct&gt; 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1…
$ .pred_0           &lt;dbl&gt; 3.604544e-01, 7.103332e-01, 9.151390e-01, 7.923568e-…
$ .pred_1           &lt;dbl&gt; 0.639545554, 0.289666770, 0.084861038, 0.207643155, …
$ species           &lt;fct&gt; Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…
$ island            &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…
$ bill_length_mm    &lt;dbl&gt; 39.1, 39.5, 40.3, 36.7, 39.3, 38.9, 39.2, 41.1, 38.6…
$ bill_depth_mm     &lt;dbl&gt; 18.7, 17.4, 18.0, 19.3, 20.6, 17.8, 19.6, 17.6, 21.2…
$ flipper_length_mm &lt;int&gt; 181, 186, 195, 193, 190, 181, 195, 182, 191, 198, 18…
$ body_mass_g       &lt;int&gt; 3750, 3800, 3250, 3450, 3650, 3625, 4675, 3200, 3800…
$ sex               &lt;fct&gt; 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0…</code></pre>
</div>
</div>
<p>Um nun eine Confusion Matrix zu erzeugen, selektieren wir zuerst die relevanten Spalten <code>.pred_class</code> und <code>sex</code> und übergeben diese der <code>table()</code> Funktion. Die <code>table()</code> Funktion erzeugt eine Kreuztabelle welche einer Confusion Matrix entspricht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.pred_class,sex) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           sex
.pred_class   0   1
          0 153  13
          1  12 155</code></pre>
</div>
</div>
<p>Nun haben wir allerdings noch folgendes Problem: In <a href="#fig-cm" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> stehen die Positives in der ersten Zeile bzw. der ersten Spalte. Die resultierende Confusion Matrix zeigt die Werte Allerdings sortiert nach Zeilen- bzw. Spaltennamen an. Wir können diese aber einfach neu anordnen indem wir den Befehl auf die zuvor selektierten Spalten anwenden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Da die Spalten <code>.pred_class</code> und <code>sex</code> Faktorvariablen sind, können wir die Werte mithilfe des <code>levels</code> Argument neu sortieren. Durch das Spezifizieren von <code>levels = c("1","0")</code> erreichen wir, dass die Reihenfolge der Zeilen und Spalten getauscht werden. Es gilt also nach dieser Transformation <code>"1"&lt;"0"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cm_lr <span class="ot">&lt;-</span> log_fit <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.pred_class,sex) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>cm_lr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           sex
.pred_class   1   0
          1 155  12
          0  13 153</code></pre>
</div>
</div>
<p>Nun haben wir zwar erreicht, dass die Einträge richtig sortiert sind, allerdings spezifizieren die Spalten in <a href="#fig-cm" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> die Predictions und die Zeilen die tatsächlichen Werte.</p>
<p>Um die Zeilen und Spalten zu vertauschen, können wir die resultierende Tabelle einfach mithilfe der <code>t()</code> Funktion transponieren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>cm_lr <span class="ot">&lt;-</span> cm_lr <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cm_lr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   .pred_class
sex   1   0
  1 155  13
  0  12 153</code></pre>
</div>
</div>
<p>Auf Basis dieser Confusion Matrix ergeben sich nun folgende Metriken:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>0.924</td>
</tr>
<tr class="even">
<td>Sensitivity</td>
<td>0.923</td>
</tr>
<tr class="odd">
<td>Specificity</td>
<td>0.927</td>
</tr>
<tr class="even">
<td>Precision</td>
<td>0.928</td>
</tr>
</tbody>
</table>
<p>Die oben aufgeführten Metriken können wir natürlich auch mithilfe von R berechnen. Damit wir nicht jede Metrik einzeln berechnen müssen, erstellen wir ein <code>metric_set</code> Objekt mithilfe der <code>metric_set()</code> Funktion, welcher wir die entsprechenden Metriken als Argumente übergeben. Um das Modell dann auf Basis dieser Menge an Metriken zu evaluieren, übergeben wir dem Objekt die Argumente <code>truth = sex</code> und <code>estimate = .pred_class</code>. Wichtig ist, dass wir wieder die Reihenfolge der Ausprägungen anpassen, um die Darstellung der Confusion Matrix aus <a href="#fig-cm" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> zu erhalten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>multi_metric <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(accuracy,sensitivity,specificity,precision)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>lr_metrics <span class="ot">&lt;-</span> log_fit <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(<span class="at">truth =</span> sex,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimate =</span> .pred_class)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>lr_metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.925
2 sensitivity binary         0.923
3 specificity binary         0.927
4 precision   binary         0.928</code></pre>
</div>
</div>
<p>Die eben berechneten Metriken basieren alle auf dem Schwellenwert <span class="math inline">\(q = 0.5\)</span>. Wir sollten deshalb auch die ROC Kurve betrachten, um ein Gefühl für verschiedene Schwellenwerte zu bekommen. Die Werte der ROC-Kurve können wir mithilfe der <code>roc_curve()</code> Funktion berechnen: Als Argument übergeben wir der Funktion die geschätzten Wahrscheinlichkeiten, dass ein Sample zur Klasse <span class="math inline">\(1\)</span> gehört und die Variable <code>sex</code>, welche die tatsächlichen Werte enthält.</p>
<p>Der Rückgabewert ist dann ein Tibble, welcher neben dem Schwellenwert <span class="math inline">\(q\)</span> gegeben durch die Spalte <code>.threshold</code> die beiden Spalten <code>specificity</code> und <code>sensitivity</code> enthält.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lr_roc <span class="ot">&lt;-</span> log_fit <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(.pred_1,<span class="at">truth =</span> sex)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>lr_roc <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 335
Columns: 3
$ .threshold  &lt;dbl&gt; -Inf, 5.839409e-06, 8.115530e-06, 9.277271e-06, 1.030156e-…
$ specificity &lt;dbl&gt; 0.000000000, 0.000000000, 0.006060606, 0.012121212, 0.0181…
$ sensitivity &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…</code></pre>
</div>
</div>
<p>Nun können wir die Kurve mithilfe von <code>ggplot</code> erzeugen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> lr_roc <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">-</span>specificity,<span class="at">y=</span>sensitivity))<span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>()<span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die <code>geom_path()</code> Funktion verbindet die Punkte in der übergebenen Reihenfolge. Wir können diese Grafik nun beliebig erweitern, um z.B. die Sensitivität und Spezifizität für den Schwellenwert <span class="math inline">\(q=0.5\)</span> hervorzuheben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>threshold_50 <span class="ot">&lt;-</span> lr_roc <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.threshold <span class="sc">==</span> <span class="fu">median</span>(.threshold)) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="dv">1</span><span class="sc">-</span>threshold_50<span class="sc">$</span>specificity,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> threshold_50<span class="sc">$</span>sensitivity,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Der Schwellenwert <span class="math inline">\(q=0.5\)</span> ist wahrscheinlich maximiert wahrscheinlich nicht gleichzeitig die Sensitivität und Spezifizität, weshalb wir diesen optimalen Wert auch berechnen und einzeichnen können. Der Punkt, welcher beide Werte simultan maximiert kann mithilfe des <code>lr_roc</code> Objektes einfach berechnet werden: Indem wir die beiden Spalten <code>specificity</code> und <code>sensitivity</code> aufsummieren und das Maximium dieser Summe berechnen, ermitteln wir den optimalen Schwellenwert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>threshold_opt <span class="ot">&lt;-</span> lr_roc <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sssum =</span> sensitivity<span class="sc">+</span>specificity) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sssum <span class="sc">==</span> <span class="fu">max</span>(sssum))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>threshold_opt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  .threshold specificity sensitivity sssum
       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
1      0.442       0.921       0.946  1.87</code></pre>
</div>
</div>
<p>Da der optimale Schwellenwert <span class="math inline">\(q=0.442\)</span> beträgt, wollen wir unsere Ergebnisse ensrsprechend anpassen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lr_metrics_new <span class="ot">&lt;-</span> log_fit <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">.pred_class =</span> <span class="fu">if_else</span>(.pred_1 <span class="sc">&gt;=</span> threshold_opt<span class="sc">$</span>.threshold,<span class="st">"1"</span>,<span class="st">"0"</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>           <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(<span class="at">truth =</span> sex,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir können dann die Ergebnisse auf Basis dieses neuen Schwellenwerts mit den Ergebnissen auf Basis des alten Schwellenwerts grafisch vergleichen:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Der Grafik können wir entnehmen, dass durch das Anpassen des Schwellenwerts zwar die Sensitivität stark gestiegen ist, allerdings die Spezifizität leicht gesunken ist. Ebenso hat sich die Accuracy verbessert, aber die Präzision leicht verschlechtert.</p>
</section>
<section id="klassifikationsbäume-1" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="klassifikationsbäume-1"><span class="header-section-number">6.6.2</span> Klassifikationsbäume</h3>
<p>Das Fitten von Klassifikationsbäumen im <code>{tidymodels}</code> Framework funktioniert analog zum Fitten von Regressionsbäumen. Lediglich das Argument <code>mode</code> muss auf <code>"classification"</code> statt <code>"regression"</code> gestetzt werden.</p>
<p>Wir trainieren zuerst einen Baum ohne die Hyperparameter gesondert zu spezifizieren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tree_spec_vanilla <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">mode =</span> <span class="st">"classification"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>tree_fit_vanilla <span class="ot">&lt;-</span> tree_spec_vanilla <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> sex<span class="sc">~</span>.,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_penguin</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das Trainierte Baummodell können wir dann wider mithilfe der <code>fancyRpartplot()</code> Funktion darstellen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>tree_fit_vanilla <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  rattle<span class="sc">::</span><span class="fu">fancyRpartPlot</span>(<span class="at">caption =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Die Knoten des dargestellten Baums sehen etwas anders aus im Vergleich zu einem Regressionsbaum: Zwar stehen der Vorhersagewert (<span class="math inline">\(0\)</span> bzw. <span class="math inline">\(1\)</span>) und die relative Anzahl der Sample im Knoten weiterhin im Knoten, allerdings wird jetzt auch noch zusätzlich die Impurity angezeigt. Die Terme in der Mitte der Knoten geben an wie groß der Anteil der jeweiligen Klassen in den verschiednen Knoten sind. So sind zum Beipiel im Knoten mit der ID <code>4</code> (linker unterer Blattknoten) <span class="math inline">\(98\%\)</span> der Samples im Knoten aus der Klasse <span class="math inline">\(0\)</span> und nur <span class="math inline">\(2\%\)</span> aus der Klasse <span class="math inline">\(1\)</span>. Umso ausgeglichener diese beiden Werte sind, desto weniger rein ist der Knoten.</p>
<p>Um eine noch bessere Performance zu erzielen, sollten die Hyperparameter <code>min_n</code>, <code>tree_depth</code> und <code>cost_complexity</code> angepasst werden. Für den folgenden Baum setzen wir deshalb die Baumtiefe auf <code>13</code>, die Mindestanzahl der Samples in einem Knoten benötigt für einen weiteren Split auf <code>3</code> und den Cost-Complexity Parameter auf <code>3.67*10^-7</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tree_spec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">tree_depth =</span> <span class="dv">13</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">min_n =</span> <span class="dv">3</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">cost_complexity =</span> <span class="fl">3.67e-7</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>tree_fit <span class="ot">&lt;-</span> tree_spec <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> sex<span class="sc">~</span>.,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_penguin</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für den resultierenden Baum ergeben sich dann die Metriken</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>tree_metrics <span class="ot">&lt;-</span> tree_fit <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(<span class="at">truth =</span> sex,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimate =</span> .pred_class)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>tree_metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.988
2 sensitivity binary         0.994
3 specificity binary         0.982
4 precision   binary         0.982</code></pre>
</div>
</div>
<p>Wir können diese Metriken grafisch mit denen der logistischen Regression vergleichen:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Der Klassifikationsbaum eignet sich also entsprechend der Metriken besser für die Vorhersage des Geschlechts eines Pinguins.</p>
</section>
<section id="neuronale-netze-1" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="neuronale-netze-1"><span class="header-section-number">6.6.3</span> Neuronale Netze</h3>
<p>Bevor wir ein Neuronales Netz trainieren können müssen wir die numerischen Feature wieder normalisieren und nominalen Feature in Dummy Variablen umwanderln. Hierfür verwenden wir wieder die <code>dummy_cols()</code> Funktion. Damit wir aber nicht die Zielvariable <code>"sex"</code> in eine Dummy Variable umwandeln, spezifizieren wir in dem Argument <code>select_columns</code> der Funktion dass nur <code>"island"</code> und <code>"spezies"</code> umgewandelt werden sollen. Zusätzlich spezifizieren wir wieder in der <code>mutate_at()</code> Funktion, dass außer der Zielvariable <code>"sex"</code> alle weiteren Variablen normalisiert werden sollen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>data_penguin_transformed <span class="ot">&lt;-</span> data_penguin <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()<span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dummy_cols</span>(<span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">"island"</span>,<span class="st">"species"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(species,island))<span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(<span class="sc">-</span><span class="st">"sex"</span>),scale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Spezifikation eines Neuronalen Netz Klassifizierers funktioniert dann analog wie im Regressionsfall. Nur das Argument <code>mode</code> muss auf <code>"classification"</code> gesetzt werden, damit die Fehlerfunktion entsprechend angepasst wird.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>nnet_spec <span class="ot">&lt;-</span> <span class="fu">mlp</span>(<span class="at">epochs =</span> <span class="dv">100</span>,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">hidden_units =</span> <span class="fu">c</span>(<span class="dv">64</span>,<span class="dv">16</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">learn_rate =</span> <span class="fl">0.075</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">activation =</span> <span class="fu">c</span>(<span class="st">"relu"</span>,<span class="st">"relu"</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">mode =</span> <span class="st">"classification"</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                 ) <span class="sc">%&gt;%</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="at">engine =</span> <span class="st">"brulee"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">optimizer =</span> <span class="st">"SGD"</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">stop_iter =</span> <span class="dv">15</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>             ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Das Fitten der Modellparameter funktioniert ebenso analog mithilfe der <code>fit</code> Funktion:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>nnet_res <span class="ot">&lt;-</span> nnet_spec <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> data_penguin_transformed,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">formula =</span> sex <span class="sc">~</span>.</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nach dem Fitten können wir dann das geschätzte Modell wieder anhand unseres <code>multi_metric</code> Objekts evaluieren:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>nnet_res <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_penguin_transformed) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, sex), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(<span class="at">truth =</span> sex,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.919
2 sensitivity binary         0.929
3 specificity binary         0.909
4 precision   binary         0.912</code></pre>
</div>
</div>
<p>Die Ergebnisse des Neuronalen Netzes sind etwas schlechter als die des Klassifikationsbaumes, wobei man bei diesem Vergleich auch vorsichtig sein muss, da man hier die Performance auf den Trainingsdaten vergleich. Da der Penguins Datensatz allerdings nur <code>344</code> Sample umfasst, kann es sein, dass die Datenmenge für das erfolgreiche Trainieren eines Neuronalen Netz Klassifizierer zu klein ist.</p>
</section>
</section>
<section id="übungsaufgaben" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="übungsaufgaben"><span class="header-section-number">6.7</span> Übungsaufgaben</h2>
<div id="exr-logistic_prob" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 6.1</strong></span> &nbsp;</p>
<ol type="1">
<li><p>Im Kontext der logistischen Regression ist die Wahrscheinlichkeit, dass ein Datenpunkt zur Klasse <span class="math inline">\(1\)</span> gehört definiert als <span class="math display">\[\begin{equation*}
\mathbb{P}(Y=1|X=x) = \frac{1}{1+\exp\left(-(b_0+\sum_{j=1}^J b_j x_j)\right)}
\end{equation*}\]</span> Zeige nun , dass <span class="math display">\[\begin{equation*}
\mathbb{P}(Y=0|X=x) = \frac{\exp\left(-\left(b_0+\sum_{j=1}^J b_j x_j\right)\right)}{1+\exp\left(-\left(b_0+\sum_{j=1}^J b_j x_j\right)\right)}
\end{equation*}\]</span></p></li>
<li><p>In <a href="#sec-lrinterp" class="quarto-xref"><span>Section 6.3.2</span></a> haben wir in Gleichung <span class="math inline">\(\eqref{eq:odds}\)</span> die Odds definiert. Zeige, dass der Quotient der Wahrscheinlichkeiten tatsächlich <span class="math inline">\(\exp(b_0+\sum_{j=1}^J b_jx_j)\)</span> ergibt.</p></li>
</ol>
</div>
<div id="exr-metrics" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 6.2</strong></span> Gegeben sei folgende Confusion Matrix:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Berechne für diese Confusion Matrix die Metriken</p>
<ul>
<li>Accuracy</li>
<li>Sensitivität</li>
<li>Spezifizität</li>
<li>Precision</li>
</ul>
<p>Runde die Ergebnisse auf drei Nachkommastellen.</p>
</div>
<p>Für die folgenden Aufgaben wollen wir ein Datensatz untersuchen, welcher anonymisierte Patientendaten von <span class="math inline">\(300\)</span> Personen enthält. Der Datensatz <code>Heart Disease Prediction Dataset</code> kann auf der Plattform <a href="https://www.kaggle.com/datasets/krishujeniya/heart-diseae">Kaggle</a>, oder über <a href="data/heart-disease.csv">diesen Link</a><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> heruntergeladen werden.</p>
<p>Der Datensatz enthält folgende Variablen:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 62%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Beschreibung</th>
<th>Ausprägung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>age</td>
<td>Alter des Patienten (in Jahren)</td>
<td>Zahl</td>
</tr>
<tr class="even">
<td>sex</td>
<td>Geschlecht des Patienten</td>
<td>1 = männlich, 0 = weiblich</td>
</tr>
<tr class="odd">
<td>cp</td>
<td>Typ der Brustschmerzen</td>
<td>1–4</td>
</tr>
<tr class="even">
<td>trestbps</td>
<td>Blutdruck in Ruhe bei Aufnahme ins Krankenhaus (in mm Hg)</td>
<td>Zahl</td>
</tr>
<tr class="odd">
<td>chol</td>
<td>Serum-Cholesterin in mg/dl</td>
<td>Zahl</td>
</tr>
<tr class="even">
<td>fbs</td>
<td>Nüchternblutzucker &gt; 120 mg/dl</td>
<td>1 = ja, 0 = nein</td>
</tr>
<tr class="odd">
<td>restecg</td>
<td>Ruhe-EKG-Ergebnisse</td>
<td>0–2</td>
</tr>
<tr class="even">
<td>thalach</td>
<td>Maximale erreichte Herzfrequenz</td>
<td>Zahl</td>
</tr>
<tr class="odd">
<td>exang</td>
<td>Belastungsinduzierte Angina</td>
<td>1 = ja, 0 = nein</td>
</tr>
<tr class="even">
<td>oldpeak</td>
<td>ST-Streckensenkung durch Belastung im Vergleich zur Ruhe</td>
<td>Zahl</td>
</tr>
</tbody>
</table>
<p>Zusätzlich enthält der Datensatz noch die Variable <code>target</code>, welche beschreibt, ob eine Person an einer Herzkrankheit leidet. Die Variable <code>target</code> hat die Ausprägungen <code>1</code> und <code>0</code>, wobei <code>1</code> für ein positives Testergebnis bzw. Krankheitsbild steht und <code>0</code> für ein negatives.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div id="exr-EDA" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 6.3</strong></span> &nbsp;</p>
<ol type="1">
<li><p>Lese den Datensatz ein und wandle die Zielvarioble <code>target</code> in eine Faktorvariable um.</p></li>
<li><p>Finde heraus, wie viele Patienten mit bzw. ohne Herzkrankheit im Datensatz vorhanden sind. Ist der Datensatz balanciert?</p></li>
<li><p>Sind in dem gegebenen Datensatz mehr Männer oder Frauen von der Herzkrankheit betroffen? Betrachte nicht nur die absolute Anzahl, sondern auch die relative Anzahl in den beiden Geschlechtsgruppen.</p></li>
<li><p>Erstelle jeweils einen Boxplot für das Alter jener Personen welche erkrankt, bzw. nicht erkankt sind. Lässt sich ein Zusammenhang zwischen dem Alter der Personen und der Krankheit anhand der Boxplots erkennen?</p></li>
</ol>
</div>
<div id="exr-logistic_reg" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 6.4</strong></span> In dieser Übung wollen wir ein logistisches Regressionsmodell schätzen, die geschätzten Parameter untersuchen und verschiedene Metriken auf Test Daten berechnen.</p>
<ol type="1">
<li><p>Teile den Datensatz in Trainings- und Testdaten ein. Verwende das Seed <code>123</code> und die Defaultparameter der <code>initial_split</code> Funktion bezüglich des Anteils der Trainings- und Testaden.</p></li>
<li><ol type="i">
<li><p>Schätze ein logistisches Regressionmodell auf Basis der Trainingsdaten.</p></li>
<li><p>Erstelle eine Summary des geschätzeten Modells und beurteile, welche Variablen statistisch signifikant sind zum Mindestniveau <span class="math inline">\(\alpha = 0.1\)</span>.</p></li>
<li><p>Angenommen die Variable <code>cp</code> erhöht sich um eine Einheit, während alle anderen Variablen gleich bleiben. Wie wirkt sich das auf die Odds aus?</p></li>
</ol></li>
<li><p>Nun wollen wir das Modell auf den Testdaten evaluieren.</p>
<ol type="i">
<li><p>Erstelle eine Confusion Matrix wie in Abschnitt <a href="#sec-confmat" class="quarto-xref"><span>Section 6.2.1</span></a> auf Basis der Testdaten.</p></li>
<li><p>Verwende das <code>multi_metric</code> Objekt aus <a href="#sec-logreg" class="quarto-xref"><span>Section 6.6.1</span></a> um eine übersicht der verschiedenen Metriken zu erstellen.</p></li>
<li><p>Hat das Modell größere Schwierigkeiten Personen als krank zu identifizieren, welche tatsächlich krank sind, oder Personen als nicht-erkrankt zu identifizieren, welche tatsächlich nicht krank sind?</p></li>
</ol></li>
</ol>
</div>
<div id="exr-classification_tree" class="theorem exercise">
<p><span class="theorem-title"><strong>Aufgabe 6.5</strong></span> &nbsp;</p>
<ol type="1">
<li><ol type="i">
<li><p>Trainiere nun einen Klassifikationsbaum mit folgenden Parametern auf den Trainingsdaten.</p>
<ul>
<li><code>cost_complexity = 6.43e-4</code>,</li>
<li><code>tree_depth = 14</code>,</li>
<li><code>min_n = 12</code></li>
</ul></li>
<li><p>Berechne nun die gleichen Metriken wie in Teilaufgabe 3. ii. aus <a href="#exr-logistic_reg" class="quarto-xref">Aufgabe&nbsp;<span>6.4</span></a> auf Basis der Testdaten.</p></li>
<li><p>Welches der beiden Modelle (logistische Regression vs.&nbsp;Entscheidungsbaum) eignet sich in diesem Kontext besser um eine Erkrankung vorherzusagen?</p></li>
</ol></li>
<li><p>Da beim Erstellen der Vorhersagen der Schwellenwert <span class="math inline">\(q = 0.5\)</span> verwendet wurde, sollen wir in dieser Teilaufgabe die ROC Kurve untersuchen.</p>
<ol type="i">
<li><p>Erstelle eine ROC-Kurve auf Basis der Testdaten wie in <a href="#sec-logreg" class="quarto-xref"><span>Section 6.6.1</span></a>.</p></li>
<li><p>Warum sind in der dargestellten ROC Kurve nur sehr wenige Spezifizitäts und Sensitivitäts Kombinationen dargestellt?</p></li>
<li><p>Bestimme anhand der folgenden Tabelle den optimalen Schwellenwert <span class="math inline">\(q\)</span> (welcher simultan die Spezifizität und Sensitivität maximiert) und stelle diesen in der ROC-Kurve der vorherigen Teilaufgabe dar.</p>
<div class="cell">
<div class="cell-output-display">
<div id="bxdvzwkvav" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#bxdvzwkvav table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#bxdvzwkvav thead, #bxdvzwkvav tbody, #bxdvzwkvav tfoot, #bxdvzwkvav tr, #bxdvzwkvav td, #bxdvzwkvav th {
  border-style: none;
}

#bxdvzwkvav p {
  margin: 0;
  padding: 0;
}

#bxdvzwkvav .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bxdvzwkvav .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#bxdvzwkvav .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bxdvzwkvav .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bxdvzwkvav .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bxdvzwkvav .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxdvzwkvav .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bxdvzwkvav .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bxdvzwkvav .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bxdvzwkvav .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bxdvzwkvav .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bxdvzwkvav .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bxdvzwkvav .gt_spanner_row {
  border-bottom-style: hidden;
}

#bxdvzwkvav .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#bxdvzwkvav .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bxdvzwkvav .gt_from_md > :first-child {
  margin-top: 0;
}

#bxdvzwkvav .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bxdvzwkvav .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bxdvzwkvav .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bxdvzwkvav .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bxdvzwkvav .gt_row_group_first td {
  border-top-width: 2px;
}

#bxdvzwkvav .gt_row_group_first th {
  border-top-width: 2px;
}

#bxdvzwkvav .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxdvzwkvav .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bxdvzwkvav .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bxdvzwkvav .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxdvzwkvav .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxdvzwkvav .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bxdvzwkvav .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#bxdvzwkvav .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bxdvzwkvav .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bxdvzwkvav .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bxdvzwkvav .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxdvzwkvav .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bxdvzwkvav .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bxdvzwkvav .gt_left {
  text-align: left;
}

#bxdvzwkvav .gt_center {
  text-align: center;
}

#bxdvzwkvav .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bxdvzwkvav .gt_font_normal {
  font-weight: normal;
}

#bxdvzwkvav .gt_font_bold {
  font-weight: bold;
}

#bxdvzwkvav .gt_font_italic {
  font-style: italic;
}

#bxdvzwkvav .gt_super {
  font-size: 65%;
}

#bxdvzwkvav .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#bxdvzwkvav .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bxdvzwkvav .gt_indent_1 {
  text-indent: 5px;
}

#bxdvzwkvav .gt_indent_2 {
  text-indent: 10px;
}

#bxdvzwkvav .gt_indent_3 {
  text-indent: 15px;
}

#bxdvzwkvav .gt_indent_4 {
  text-indent: 20px;
}

#bxdvzwkvav .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id=".threshold" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">.threshold</th>
<th id="specificity" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">specificity</th>
<th id="sensitivity" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">sensitivity</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers=".threshold">−Inf</td>
<td class="gt_row gt_right" headers="specificity">0.000</td>
<td class="gt_row gt_right" headers="sensitivity">1.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers=".threshold">0.082</td>
<td class="gt_row gt_right" headers="specificity">0.000</td>
<td class="gt_row gt_right" headers="sensitivity">1.000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers=".threshold">0.143</td>
<td class="gt_row gt_right" headers="specificity">0.429</td>
<td class="gt_row gt_right" headers="sensitivity">0.951</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers=".threshold">0.235</td>
<td class="gt_row gt_right" headers="specificity">0.457</td>
<td class="gt_row gt_right" headers="sensitivity">0.951</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers=".threshold">0.417</td>
<td class="gt_row gt_right" headers="specificity">0.543</td>
<td class="gt_row gt_right" headers="sensitivity">0.927</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers=".threshold">0.686</td>
<td class="gt_row gt_right" headers="specificity">0.571</td>
<td class="gt_row gt_right" headers="sensitivity">0.854</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers=".threshold">0.892</td>
<td class="gt_row gt_right" headers="specificity">0.657</td>
<td class="gt_row gt_right" headers="sensitivity">0.610</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers=".threshold">0.917</td>
<td class="gt_row gt_right" headers="specificity">0.943</td>
<td class="gt_row gt_right" headers="sensitivity">0.024</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers=".threshold">Inf</td>
<td class="gt_row gt_right" headers="specificity">1.000</td>
<td class="gt_row gt_right" headers="sensitivity">0.000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div></li>
<li><p>Ist der optimale Schwellenwert größer oder kleiner als <span class="math inline">\(0.5\)</span>?</p></li>
</ol></li>
</ol>
</div>
</section>
<section id="lösungen" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="lösungen"><span class="header-section-number">6.8</span> Lösungen</h2>
<div id="sol-logistic_prob" class="proof solution">
<p><span class="proof-title"><em>Solution 6.1</em> (<a href="#exr-logistic_prob" class="quarto-xref">Aufgabe&nbsp;<span>6.1</span></a>). </span></p>
<ol type="1">
<li><p>Gegeben ist die Wahrscheinlichkeit für die Klasse <span class="math inline">\(1\)</span> in einem logistischen Regressionsmodell: <span class="math display">\[\begin{equation*}
\mathbb{P}(Y=1|X=x) = \frac{1}{1+\exp\left(-(b_0+\sum_{j=1}^J b_j x_j)\right)}
\end{equation*}\]</span> Da es sich um ein binäres Klassifikationsproblem handelt, gilt: <span class="math display">\[\begin{equation*}
\mathbb{P}(Y=0|X=x) = 1 - \mathbb{P}(Y=1|X=x)
\end{equation*}\]</span> Setze die gegebene Formel ein: <span class="math display">\[\begin{align*}
\mathbb{P}(Y=0|X=x)
&amp;= 1 - \frac{1}{1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)} \\
&amp;= \frac{\left(1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)\right) - 1}{1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)} \\
&amp;= \frac{\exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)}{1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)}
\end{align*}\]</span></p></li>
<li><p>Es gilt: <span class="math display">\[\begin{align*}
\frac{\mathbb{P}(Y=1|X=x)}{\mathbb{P}(Y=0|X=x)}
&amp;= \frac{
   \dfrac{1}{1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)}
}{
   \dfrac{\exp\left(-\left(b_0 + \sum_{j=1}^J b_j x_j\right)\right)}{1 + \exp\left(-\left(b_0 + \sum_{j=1}^J b_j x_j\right)\right)}
} \\
&amp;= \frac{1 + \exp\left(-\left(b_0 + \sum_{j=1}^J b_j x_j\right)\right)}{\exp\left(-\left(b_0 + \sum_{j=1}^J b_j x_j\right)\right)} \cdot \frac{1}{1 + \exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)} \\
&amp;= \frac{1}{\exp\left(-(b_0 + \sum_{j=1}^J b_j x_j)\right)} \\
&amp;= \exp\left(b_0 + \sum_{j=1}^J b_j x_j\right)
\end{align*}\]</span></p></li>
</ol>
</div>
<div id="sol-metrics" class="proof solution">
<p><span class="proof-title"><em>Solution 6.2</em> (<a href="#exr-metrics" class="quarto-xref">Aufgabe&nbsp;<span>6.2</span></a>). </span></p>
<div class="cell">
<div class="cell-output-display">
<div id="xsrpcabbhz" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xsrpcabbhz table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xsrpcabbhz thead, #xsrpcabbhz tbody, #xsrpcabbhz tfoot, #xsrpcabbhz tr, #xsrpcabbhz td, #xsrpcabbhz th {
  border-style: none;
}

#xsrpcabbhz p {
  margin: 0;
  padding: 0;
}

#xsrpcabbhz .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xsrpcabbhz .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xsrpcabbhz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xsrpcabbhz .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xsrpcabbhz .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xsrpcabbhz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xsrpcabbhz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xsrpcabbhz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xsrpcabbhz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xsrpcabbhz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xsrpcabbhz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xsrpcabbhz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xsrpcabbhz .gt_spanner_row {
  border-bottom-style: hidden;
}

#xsrpcabbhz .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xsrpcabbhz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xsrpcabbhz .gt_from_md > :first-child {
  margin-top: 0;
}

#xsrpcabbhz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xsrpcabbhz .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xsrpcabbhz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xsrpcabbhz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xsrpcabbhz .gt_row_group_first td {
  border-top-width: 2px;
}

#xsrpcabbhz .gt_row_group_first th {
  border-top-width: 2px;
}

#xsrpcabbhz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xsrpcabbhz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xsrpcabbhz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xsrpcabbhz .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xsrpcabbhz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xsrpcabbhz .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xsrpcabbhz .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xsrpcabbhz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xsrpcabbhz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xsrpcabbhz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xsrpcabbhz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xsrpcabbhz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xsrpcabbhz .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xsrpcabbhz .gt_left {
  text-align: left;
}

#xsrpcabbhz .gt_center {
  text-align: center;
}

#xsrpcabbhz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xsrpcabbhz .gt_font_normal {
  font-weight: normal;
}

#xsrpcabbhz .gt_font_bold {
  font-weight: bold;
}

#xsrpcabbhz .gt_font_italic {
  font-style: italic;
}

#xsrpcabbhz .gt_super {
  font-size: 65%;
}

#xsrpcabbhz .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xsrpcabbhz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xsrpcabbhz .gt_indent_1 {
  text-indent: 5px;
}

#xsrpcabbhz .gt_indent_2 {
  text-indent: 10px;
}

#xsrpcabbhz .gt_indent_3 {
  text-indent: 15px;
}

#xsrpcabbhz .gt_indent_4 {
  text-indent: 20px;
}

#xsrpcabbhz .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_col_headings">
<th id="Metrik" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Metrik</th>
<th id="Wert" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Wert</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Metrik">accuracy</td>
<td class="gt_row gt_right" headers="Wert">0.838</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Metrik">sensitivity</td>
<td class="gt_row gt_right" headers="Wert">0.880</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Metrik">specificity</td>
<td class="gt_row gt_right" headers="Wert">0.793</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Metrik">precision</td>
<td class="gt_row gt_right" headers="Wert">0.819</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="sol-EDA" class="proof solution">
<p><span class="proof-title"><em>Solution 6.3</em> (<a href="#exr-EDA" class="quarto-xref">Aufgabe&nbsp;<span>6.3</span></a>). </span></p>
<ol type="1">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>data_heart <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/heart-disease.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">target =</span> <span class="fu">factor</span>(target))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data_heart <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(target) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  target     n
  &lt;fct&gt;  &lt;int&gt;
1 0        138
2 1        165</code></pre>
</div>
</div>
<p>In dem Datensatz sind mehr Personen ohne der Krankheit als Personen mit der Krankheit.</p></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>data_heart <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex,target) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   sex [2]
    sex target     n
  &lt;int&gt; &lt;fct&gt;  &lt;int&gt;
1     0 0         24
2     0 1         72
3     1 0        114
4     1 1         93</code></pre>
</div>
</div>
<p>Im Datensatz leiden <span class="math inline">\(93\)</span> Männer an der Herzkrankheit, während bei den Frauen nur <span class="math inline">\(72\)</span> Personen an der Krankheit leiden.</p>
<p>Um die relativen Anteile zu bestimmen, müssen wir die obige Syntax etwas anpassen. In der <code>summarise()</code> Funktion können wir mithilfe des <code>.groups = "drop_last"</code> Arguments die Gruppierung bezüglich der Variable <code>target</code> auflösen (da diese die letzte Gruppe ist). Der Summary Datensatz enthält nach dieser Operation also nur noch die Gruppe bezüglich der Variable <code>sex</code>. Wenn wir dann auf diesen Datensatz die <code>mutate()</code> Funktion anwenden, dann werden die in der <code>mutate()</code> spezifizierten Funktionen Gruppenweise angewendet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data_heart <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, target) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop_last"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">freq =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   sex [2]
    sex target     n  freq
  &lt;int&gt; &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt;
1     0 0         24 0.25 
2     0 1         72 0.75 
3     1 0        114 0.551
4     1 1         93 0.449</code></pre>
</div>
</div>
<p>Obwohl also absolut gesehen die Anzahl der erkrankten Personen in der Gruppe der Männer größer ist, (<span class="math inline">\(93\)</span> vs.&nbsp;<span class="math inline">\(72\)</span>) ist der relative Anteil unter den Frauen viel höher (<span class="math inline">\(75\%\)</span> vs.&nbsp;<span class="math inline">\(44.9\%\)</span>).</p></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data_heart <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>target,<span class="at">y=</span>age))<span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Der Altersmedian in der Gruppe der erkankten Person ist niedriger als in der Gruppe der Personen welche nicht an der Krankheit leiden. Auch die anderen beiden Quartile der Gruppe der erkrankten Personen sind im gegebenen Datensatz niedriger als die der Gruppe der nicht erkrankten Personen. Man könnte also vermuten, dass die Krankheit vermehrt bei jüngern Leuten auftritt.</p></li>
</ol>
</div>
<div id="sol-logistic_reg" class="proof solution">
<p><span class="proof-title"><em>Solution 6.4</em> (<a href="#exr-logistic_reg" class="quarto-xref">Aufgabe&nbsp;<span>6.4</span></a>). </span></p>
<ol type="1">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>split_heart <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data_heart)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> <span class="fu">training</span>(split_heart)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(split_heart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><ol type="i">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>log_spec <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>()</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>log_fit <span class="ot">&lt;-</span> log_spec <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> data_train,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">formula =</span> target <span class="sc">~</span>.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = target ~ ., family = stats::binomial, data = data)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.3143  -0.3945   0.1470   0.5640   2.5546  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  4.870921   2.965683   1.642 0.100501    
age         -0.013524   0.027092  -0.499 0.617656    
sex         -1.517896   0.551637  -2.752 0.005930 ** 
cp           0.800679   0.205740   3.892 9.95e-05 ***
trestbps    -0.024524   0.011616  -2.111 0.034745 *  
chol        -0.002865   0.004507  -0.636 0.525027    
fbs          0.092637   0.595299   0.156 0.876337    
restecg      0.743640   0.416802   1.784 0.074398 .  
thalach      0.025976   0.012428   2.090 0.036603 *  
exang       -1.178701   0.478019  -2.466 0.013671 *  
oldpeak     -0.719277   0.252574  -2.848 0.004402 ** 
slope        0.219195   0.429168   0.511 0.609530    
ca          -0.623691   0.214508  -2.908 0.003643 ** 
thal        -1.187637   0.354814  -3.347 0.000816 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 312.74  on 226  degrees of freedom
Residual deviance: 155.52  on 213  degrees of freedom
AIC: 183.52

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Lediglich die Variablen <code>age</code>, <code>chol</code>, <code>fbs</code> und <code>slope</code> sind nicht zu einem Singifikanzniveau <span class="math inline">\(\alpha&lt;0.1\)</span> statistisch signifikant.</p></li>
<li><!-- -->
<p>Es gilt <span class="math inline">\(\hat{b}_{\verb|cp|} \approx 0.801\)</span> und deshalb <span class="math inline">\(\exp(\hat{b}_{\verb|cp|}) \approx 2.43\)</span>. Die Odds steigen also um <span class="math inline">\(2.43\)</span>.</p></li>
</ol></li>
<li><ol type="i">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(.pred_class,target))<span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, target), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>))))<span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           target
.pred_class  1  0
          1 37 10
          0  4 25</code></pre>
</div>
</div></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>log_fit <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, target), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(<span class="at">truth =</span> target,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">estimate =</span> .pred_class) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.816
2 sensitivity binary         0.902
3 specificity binary         0.714
4 precision   binary         0.787</code></pre>
</div>
</div></li>
<li>Da Sensitivität <span class="math inline">\(&gt;\)</span> Spezifizität ist das Modell besser darin die True Positives korrekt zu erkennen. In einem Medizinischen Kontext ist das wünschenswert, da so weniger tatsächlich erkrankte Personen als nicht erkrankt identifiziert werden.</li>
</ol></li>
</ol>
</div>
<div id="sol-classification_tree" class="proof solution">
<p><span class="proof-title"><em>Solution 6.5</em> (<a href="#exr-classification_tree" class="quarto-xref">Aufgabe&nbsp;<span>6.5</span></a>). </span></p>
<ol type="1">
<li><ol type="i">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>tree_spec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">mode =</span> <span class="st">"classification"</span>,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">cost_complexity =</span> <span class="fl">6.43e-4</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">tree_depth =</span> <span class="dv">14</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">min_n =</span> <span class="dv">22</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>tree_res <span class="ot">&lt;-</span> tree_spec <span class="sc">%&gt;%</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> data_train,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">formula =</span> target<span class="sc">~</span>.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>tree_res <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, target), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">multi_metric</span>(<span class="at">truth =</span> target,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">estimate =</span> .pred_class) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.724
2 sensitivity binary         0.854
3 specificity binary         0.571
4 precision   binary         0.7  </code></pre>
</div>
</div></li>
<li>Das logistische Regressionsmodell eigenet sich besser, da alle Metriken auf den Testdaten besser sind als die des Klassifikationsbaums.</li>
</ol></li>
<li><ol type="i">
<li><!-- -->
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>tree_roc <span class="ot">&lt;-</span> tree_res <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(.pred_class, target), <span class="sc">~</span> <span class="fu">factor</span>(., <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"0"</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(.pred_1,<span class="at">truth =</span> target)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> tree_roc <span class="sc">%&gt;%</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">-</span>specificity,<span class="at">y=</span>sensitivity))<span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>()<span class="sc">+</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p>In der ROC-Kurve sind nur wenige Kombinationen dargestellt, da der trainierte Baum nur wenige Schätzwerte für die Wahrscheinlichkeiten enthält. Die Anzahl der Schätzwerte ist durch die Anzahl der Blattknoten gegeben. Im Vergleich zur logistischen Regression ergeben sich also eine geringere Anzahl an Schwellenwerten die zu einer Veränderung der Spezifizität und Sensitivität führen.</p></li>
<li><p>Den optimalen Schwellenwert kann man ermitteln indem man die Summe von Spezifizität und Sensitivität betrachtet. Beim größten Summenwert kann dann der entsprechende Schwellenwert abgelesen werden. Dieser maximale Summenwert ist durch <span class="math inline">\(1.47\)</span> gegeben, was dem Schwellenwert <span class="math inline">\(q=0.417\)</span> entspricht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="dv">1</span><span class="fl">-0.543</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fl">0.927</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06_Klassifikation_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p>Ist der optimale Schwellenwert größer oder kleiner als <span class="math inline">\(0.5\)</span>?</p>
<p>Der optimale Schwellenwert <span class="math inline">\(q_{\verb|opt|}=0.417\)</span> ist kleiner als <span class="math inline">\(0.5\)</span>.</p></li>
</ol></li>
</ol>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Datensätze bei welchen weitaus mehr Negatives als Positives vertreten sind<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Funktioniert nur in der Web Version des Skripts<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>positives Krankheitsbild heißt hier, dass eine Person erkrankt ist.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05_Neuronale_Netze.html" class="pagination-link" aria-label="Neuronale Netze">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Neuronale Netze</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2025, Linus Lach</p>
<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>