<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Linear Models – Machine Learning Supplementary Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_regularization.html" rel="next">
<link href="./01_prerequisites.html" rel="prev">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-RKE6FHR659"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-RKE6FHR659', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02_linear_models.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine Learning Supplementary Material</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_prerequisites.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Important R concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_linear_models.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regularization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_regression_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regression Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_bagging_rf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">2.1</span> Overview</a></li>
  <li><a href="#good-practices-for-applied-machine-learning" id="toc-good-practices-for-applied-machine-learning" class="nav-link" data-scroll-target="#good-practices-for-applied-machine-learning"><span class="header-section-number">2.2</span> Good practices for applied Machine Learning</a>
  <ul>
  <li><a href="#developing-a-model-what-we-have-done-so-far" id="toc-developing-a-model-what-we-have-done-so-far" class="nav-link" data-scroll-target="#developing-a-model-what-we-have-done-so-far"><span class="header-section-number">2.2.1</span> Developing a model (What we have done so far!):</a></li>
  <li><a href="#developing-a-model-what-we-want-to-do-moving-forward" id="toc-developing-a-model-what-we-want-to-do-moving-forward" class="nav-link" data-scroll-target="#developing-a-model-what-we-want-to-do-moving-forward"><span class="header-section-number">2.2.2</span> Developing a model (What we want to do moving forward!):</a></li>
  </ul></li>
  <li><a href="#introduction-to-model-development-with-tidymodels" id="toc-introduction-to-model-development-with-tidymodels" class="nav-link" data-scroll-target="#introduction-to-model-development-with-tidymodels"><span class="header-section-number">2.3</span> Introduction to model development with <code>{tidymodels}</code></a>
  <ul>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">2.3.1</span> Data Exploration</a></li>
  <li><a href="#training-a-simple-linear-model" id="toc-training-a-simple-linear-model" class="nav-link" data-scroll-target="#training-a-simple-linear-model"><span class="header-section-number">2.3.2</span> Training a simple linear model</a></li>
  <li><a href="#evaluating-a-model" id="toc-evaluating-a-model" class="nav-link" data-scroll-target="#evaluating-a-model"><span class="header-section-number">2.3.3</span> Evaluating a model</a>
  <ul class="collapse">
  <li><a href="#creating-a-summary-of-the-model-parameters" id="toc-creating-a-summary-of-the-model-parameters" class="nav-link" data-scroll-target="#creating-a-summary-of-the-model-parameters"><span class="header-section-number">2.3.3.1</span> Creating a summary of the model parameters</a></li>
  <li><a href="#using-metric-sets-and-glance" id="toc-using-metric-sets-and-glance" class="nav-link" data-scroll-target="#using-metric-sets-and-glance"><span class="header-section-number">2.3.3.2</span> Using metric sets and glance</a></li>
  </ul></li>
  <li><a href="#sec-tts" id="toc-sec-tts" class="nav-link" data-scroll-target="#sec-tts"><span class="header-section-number">2.3.4</span> Training and test split</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation"><span class="header-section-number">2.3.5</span> Cross validation</a>
  <ul class="collapse">
  <li><a href="#creating-a-cross-validation-set-in-r" id="toc-creating-a-cross-validation-set-in-r" class="nav-link" data-scroll-target="#creating-a-cross-validation-set-in-r"><span class="header-section-number">2.3.5.1</span> Creating a cross validation set in R</a></li>
  <li><a href="#training-a-model-using-cross-validation" id="toc-training-a-model-using-cross-validation" class="nav-link" data-scroll-target="#training-a-model-using-cross-validation"><span class="header-section-number">2.3.5.2</span> Training a model using cross validation</a></li>
  </ul></li>
  <li><a href="#polynomial-regression-and-the-bias-variance-trade-off" id="toc-polynomial-regression-and-the-bias-variance-trade-off" class="nav-link" data-scroll-target="#polynomial-regression-and-the-bias-variance-trade-off"><span class="header-section-number">2.3.6</span> Polynomial regression and the bias variance trade off</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">2.4</span> Exercises</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions"><span class="header-section-number">2.5</span> Solutions</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">2.6</span> Session Info</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">2.1</span> Overview</h2>
<p>In this exercise session, we will review linear regression and polynomial regression. We will also learn how to efficiently split our data into training and test data, how to perform cross-validation, and why that is important. Before we dive into the details, we will discuss developing statistical models in R.</p>
</section>
<section id="good-practices-for-applied-machine-learning" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="good-practices-for-applied-machine-learning"><span class="header-section-number">2.2</span> Good practices for applied Machine Learning</h2>
<p>In previous courses, we mainly focused on fitting a certain model to a given dataset. However, this process could be described as model specification rather than model development. So, what is the difference between specifying and building a model?</p>
<section id="developing-a-model-what-we-have-done-so-far" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="developing-a-model-what-we-have-done-so-far"><span class="header-section-number">2.2.1</span> Developing a model (What we have done so far!):</h3>
<ul>
<li><p>The given dataset has been cleaned, transformed, and manipulated using various packages and libraries.</p></li>
<li><p>Resampling methods (like the ones we consider today) have been applied, but training the model on each subset or newly generated dataset is usually performed using a <em>for-loop</em> or similar methods. Loops should mostly be avoided in programming languages like R since they can be slow compared to optimized methods specifically written for higher performance.</p></li>
<li><p>Similar to applying resampling methods, hyperparameter tuning is usually performed in the same fashion.</p></li>
</ul>
<p>In summary, we have only specified the model we want to train and used a somewhat arbitrary and inconsistent approach for everything else.</p>
<p>One of the most significant issues we face, however, is when switching the model. The approach we have been using so far emphasizes working with one selected model that we wish to keep using after data preprocessing.</p>
</section>
<section id="developing-a-model-what-we-want-to-do-moving-forward" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="developing-a-model-what-we-want-to-do-moving-forward"><span class="header-section-number">2.2.2</span> Developing a model (What we want to do moving forward!):</h3>
<p>The main difference between the old and new approaches is leveraging the advantages of the <code>{tidyverse}</code> and <code>{tidymodels}</code> frameworks. These frameworks allow for consistently preprocessing the data, setting model specifications, and performing steps like resampling and hyperparameter tuning simultaneously.</p>
<p>Another huge advantage is that we can swiftly switch between different ML models by following this procedure. For example, applying a random forest algorithm and switching to a neural network approach for the same data is only a matter of changing a few lines of code, as we will see in later exercises.</p>
<p>So, where is the catch? At first, the process might seem complicated or even “overkill” for the models we use. However, as the lecture progresses, our models will also (at least sometimes) become increasingly sophisticated. We want to get used to this new process as early as possible, as it will be useful once we consider more sophisticated models.</p>
<p>The biggest takeaways are:</p>
<ul>
<li><p><strong>Consistency:</strong> Independent of what the dataset or desired model looks like, we can (almost) always use the same procedure when building a model.</p></li>
<li><p><strong>Effectiveness:</strong> Once we get used to this new approach, we can develop our models more effectively.</p></li>
<li><p><strong>Safety:</strong> Developing an ML model has many pitfalls and potholes on the way, and by design, <code>{tidymodels}</code> helps us to avoid those.</p></li>
</ul>
<p>We will introduce and explore some of the concepts above in this session’s exercises and dive deeper in later sessions.</p>
</section>
</section>
<section id="introduction-to-model-development-with-tidymodels" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="introduction-to-model-development-with-tidymodels"><span class="header-section-number">2.3</span> Introduction to model development with <code>{tidymodels}</code></h2>
<p>This section briefly introduces the most important concepts when working with the <code>{tidymodels}</code> framework.</p>
<p>The data set for this introduction is called “Wine Quality White,” and it contains roughly 5,000 different white wines tested for their physicochemical properties, such as citric acid, pH value, and density. After assessing these properties, experts rated the wine quality and assigned a score between <span class="math inline">\(0\)</span> and <span class="math inline">\(10\)</span>, where <span class="math inline">\(0\)</span> is the lowest, and <span class="math inline">\(10\)</span> is the highest score a wine can achieve.</p>
<p>The data set can be downloaded directly from the <a href="https://archive.ics.uci.edu/dataset/186/wine+quality">UC Irvine Machine Learning Repository</a> or by clicking the button below.</p>
<div style="text-align: center;">
<p><a href="data/winequality-white.csv" class="btn btn-outline-primary" role="button" data-toggle="tooltip" title="270 KB">Download Wine Data</a></p>
</div>
<section id="data-exploration" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="data-exploration"><span class="header-section-number">2.3.1</span> Data Exploration</h3>
<p>Since the data set is relatively nice in that we do not have to do much cleaning, we will keep this section relatively short.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidymodels"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggtext' was built under R version 4.4.1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data_wine <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/winequality-white.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_wine <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,898
Columns: 12
$ fixed.acidity        &lt;dbl&gt; 7.0, 6.3, 8.1, 7.2, 7.2, 8.1, 6.2, 7.0, 6.3, 8.1,…
$ volatile.acidity     &lt;dbl&gt; 0.27, 0.30, 0.28, 0.23, 0.23, 0.28, 0.32, 0.27, 0…
$ citric.acid          &lt;dbl&gt; 0.36, 0.34, 0.40, 0.32, 0.32, 0.40, 0.16, 0.36, 0…
$ residual.sugar       &lt;dbl&gt; 20.70, 1.60, 6.90, 8.50, 8.50, 6.90, 7.00, 20.70,…
$ chlorides            &lt;dbl&gt; 0.045, 0.049, 0.050, 0.058, 0.058, 0.050, 0.045, …
$ free.sulfur.dioxide  &lt;dbl&gt; 45, 14, 30, 47, 47, 30, 30, 45, 14, 28, 11, 17, 1…
$ total.sulfur.dioxide &lt;dbl&gt; 170, 132, 97, 186, 186, 97, 136, 170, 132, 129, 6…
$ density              &lt;dbl&gt; 1.0010, 0.9940, 0.9951, 0.9956, 0.9956, 0.9951, 0…
$ pH                   &lt;dbl&gt; 3.00, 3.30, 3.26, 3.19, 3.19, 3.26, 3.18, 3.00, 3…
$ sulphates            &lt;dbl&gt; 0.45, 0.49, 0.44, 0.40, 0.40, 0.44, 0.47, 0.45, 0…
$ alcohol              &lt;dbl&gt; 8.8, 9.5, 10.1, 9.9, 9.9, 10.1, 9.6, 8.8, 9.5, 11…
$ quality              &lt;int&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 7, 5, 7, 6…</code></pre>
</div>
</div>
<p>Except for the <code>quality</code> variable, every other variable is of type double.</p>
</section>
<section id="training-a-simple-linear-model" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="training-a-simple-linear-model"><span class="header-section-number">2.3.2</span> Training a simple linear model</h3>
<p>For this example we build a linear model to predict the alcohol content of the wines. Recall the model equation <span class="math display">\[\begin{equation}
  y = \beta_0 + \beta_1 x_1 + ... + \beta_n x_n + \varepsilon,
\end{equation}\]</span></p>
<p>where <span class="math inline">\(x_1,...,x_n\in\mathbb{R}^k\)</span> denotes <span class="math inline">\(n\)</span> different features with <span class="math inline">\(k\)</span> samples, <span class="math inline">\(\varepsilon \sim \mathcal{N}(0,1)\)</span> a <span class="math inline">\(k\)</span>-dimensional error term and <span class="math inline">\(\beta_0,...,\beta_n\)</span> the <span class="math inline">\(n+1\)</span> model parameters. In our example, <span class="math inline">\(y\)</span> denotes the variable <code>alcohol</code>, <span class="math inline">\(k= 4898\)</span>, and <span class="math inline">\(n = 11\)</span>.</p>
<p>The <code>{parsnip}</code> packages which is part of <code>{tidymodels}</code> contains the function <code>linear_reg</code> which creates a linear model when called.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>lm_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Computational engine: lm </code></pre>
</div>
</div>
<p>Only calling the function name does not help much when trying to model the alcohol contents of the wine, since we haven’t specified the input variables, output variable, and data used for the regression.</p>
<p>To add these, we can use the <code>%&gt;%</code> pipe operator and <code>fit</code> function. As discussed in the previous exercise, the pipe operator passes the output of one operation in the other. Therefore, passing the <code>lm_mod</code> object into the <code>fit</code> function, specifies that the <code>fit</code> function fits a linear model. Fitting in that context refers to estimating the parameters <span class="math inline">\(\beta_0,...,\beta_n\)</span>. Besides the model specification, arguments for the <code>fit</code> function contain the <code>formula</code> which specifies the independent and dependent variables and the <code>data</code> argument which specifies the data that is used for training the model.</p>
<p>The formula in the code cell below specifies that we want to regress <code>alcohol</code> on every other variable indicated by the <code>.</code> after <code>~</code>. <code>~</code> (tilde) is used to separate the left- and right-hand sides in the model formula.</p>
<p>As <code>data</code> we simply pass the whole <code>data_wine</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a> <span class="at">formula =</span> alcohol <span class="sc">~</span>.,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a> <span class="at">data =</span> data_wine</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>lm_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = alcohol ~ ., data = data)

Coefficients:
         (Intercept)         fixed.acidity      volatile.acidity  
           6.719e+02             5.099e-01             9.636e-01  
         citric.acid        residual.sugar             chlorides  
           3.658e-01             2.341e-01            -1.832e-01  
 free.sulfur.dioxide  total.sulfur.dioxide               density  
          -3.665e-03             6.579e-04            -6.793e+02  
                  pH             sulphates               quality  
           2.383e+00             9.669e-01             6.663e-02  </code></pre>
</div>
</div>
<p>The return value is a <code>parsnip model object</code> that prints the model coefficients <span class="math inline">\(\beta_0,...,\beta_n\)</span> when called.</p>
<p>Instead of fitting the linear model on all parameters using <code>.</code>, we can also specify the relationship between the independent variables using arithmetic notation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> <span class="at">formula =</span> alcohol <span class="sc">~</span> fixed.acidity<span class="sc">+</span>volatile.acidity<span class="sc">+</span>citric.acid<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>   residual.sugar<span class="sc">+</span>chlorides<span class="sc">+</span>free.sulfur.dioxide<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>   total.sulfur.dioxide<span class="sc">+</span>density<span class="sc">+</span>pH<span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>   sulphates<span class="sc">+</span>quality,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a> <span class="at">data =</span> data_wine</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, that this notation does not fall under <em>best practices of model development</em> as it is more advisable to create a separate data set for training and fit the model on every variable contained using the <code>.</code> notation.</p>
</section>
<section id="evaluating-a-model" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="evaluating-a-model"><span class="header-section-number">2.3.3</span> Evaluating a model</h3>
<section id="creating-a-summary-of-the-model-parameters" class="level4" data-number="2.3.3.1">
<h4 data-number="2.3.3.1" class="anchored" data-anchor-id="creating-a-summary-of-the-model-parameters"><span class="header-section-number">2.3.3.1</span> Creating a summary of the model parameters</h4>
<p>Using the <code>tidy</code> function on the fitted model returns an overview of the model parameters including <span class="math inline">\(p\)</span>-values and the <span class="math inline">\(t\)</span>-statistic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   term                    estimate std.error statistic  p.value
   &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)           672.        5.56       121.    0       
 2 fixed.acidity           0.510     0.00986     51.7   0       
 3 volatile.acidity        0.964     0.0672      14.3   1.00e-45
 4 citric.acid             0.366     0.0560       6.54  6.88e-11
 5 residual.sugar          0.234     0.00296     79.1   0       
 6 chlorides              -0.183     0.321       -0.571 5.68e- 1
 7 free.sulfur.dioxide    -0.00366   0.000494    -7.42  1.33e-13
 8 total.sulfur.dioxide    0.000658  0.000222     2.97  3.01e- 3
 9 density              -679.        5.70      -119.    0       
10 pH                      2.38      0.0519      45.9   0       
11 sulphates               0.967     0.0575      16.8   1.02e-61
12 quality                 0.0666    0.00834      7.99  1.70e-15</code></pre>
</div>
</div>
<p>Recall that the <code>statistic</code> column refers to the <span class="math inline">\(t\)</span>-statistic which corresponds to the following hypotheses for any <span class="math inline">\(\hat{\beta}_i,\, i=1,...,12\)</span>: <span class="math display">\[\begin{equation*}
H_0:\, \hat{\beta}_i= 0\qquad \mathrm{vs.}\qquad H_1:\, \hat{\beta}_i \neq 0.
\end{equation*}\]</span> If the <span class="math inline">\(p\)</span>–value regarding this test is low, we can confidently reject the null hypothesis.</p>
<p>Similar to the <code>tidy</code> function, the <code>summary</code> function can be called on the <code>fit</code> attribute of the model, which also returns a summary which contains a few more details, such as the <span class="math inline">\(F\)</span>-statistic, <span class="math inline">\(R^2\)</span>, and residual standard error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lm_mod<span class="sc">$</span>fit <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = alcohol ~ fixed.acidity + volatile.acidity + 
    citric.acid + residual.sugar + chlorides + free.sulfur.dioxide + 
    total.sulfur.dioxide + density + pH + sulphates + quality, 
    data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.3343 -0.2553 -0.0255  0.2214 15.7789 

Coefficients:
                       Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)           6.719e+02  5.563e+00  120.790  &lt; 2e-16 ***
fixed.acidity         5.099e-01  9.855e-03   51.745  &lt; 2e-16 ***
volatile.acidity      9.636e-01  6.718e-02   14.342  &lt; 2e-16 ***
citric.acid           3.658e-01  5.596e-02    6.538 6.88e-11 ***
residual.sugar        2.341e-01  2.960e-03   79.112  &lt; 2e-16 ***
chlorides            -1.832e-01  3.207e-01   -0.571  0.56785    
free.sulfur.dioxide  -3.665e-03  4.936e-04   -7.425 1.33e-13 ***
total.sulfur.dioxide  6.579e-04  2.217e-04    2.968  0.00301 ** 
density              -6.793e+02  5.696e+00 -119.259  &lt; 2e-16 ***
pH                    2.383e+00  5.191e-02   45.916  &lt; 2e-16 ***
sulphates             9.669e-01  5.751e-02   16.814  &lt; 2e-16 ***
quality               6.663e-02  8.341e-03    7.988 1.70e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4409 on 4886 degrees of freedom
Multiple R-squared:  0.8719,    Adjusted R-squared:  0.8716 
F-statistic:  3024 on 11 and 4886 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To extract these statistics in <em>tidy</em> fashion, the <code>{yardsticks}</code> library (see Exercise Session 01) can help.</p>
</section>
<section id="using-metric-sets-and-glance" class="level4" data-number="2.3.3.2">
<h4 data-number="2.3.3.2" class="anchored" data-anchor-id="using-metric-sets-and-glance"><span class="header-section-number">2.3.3.2</span> Using metric sets and glance</h4>
<p>Instead of using the <code>summary</code> function on the <code>fit</code> attribute to extract certain metrics, we can also use the <code>metric_set</code> function. First, define a metric set by passing different metrics such as <code>rsq</code>, <code>rmse</code>, and <code>mae</code> into the <code>metric_set</code> function. Then, pass the predictions of the model into this newly defined metric set which returns the specified metrics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>multi_metric <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rsq,rmse,mae)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_wine) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(.pred,alcohol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rsq     standard       0.872
2 rmse    standard       0.440
3 mae     standard       0.294</code></pre>
</div>
</div>
<p>A general metric set can be created using the <code>glance</code> function which returns a comprehensive list of metrics for the underlying model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lm_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.872         0.872 0.441     3024.       0    11 -2933. 5892. 5976.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="sec-tts" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="sec-tts"><span class="header-section-number">2.3.4</span> Training and test split</h3>
<p>Splitting the data into three different subsets, called <em>training</em>, <em>validation</em>, and <em>testing</em> data, is a crucial aspect in Machine Learning.</p>
<div id="fig-trainingsplit" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trainingsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pictures/train_val_test_split.svg" id="fig-trainingsplit" class="img-fluid quarto-figure quarto-figure-center anchored figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-trainingsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1
</figcaption>
</figure>
</div>
<p>The basic idea is to train the model on the training data, validate the results on the validation data, and finally test the performance on the testing data that has previously not been observed.</p>
<p>Without this separation the model might become prone to overfitting meaning that the model does not perform well on previously unseen data.</p>
<p>The general procedure for training and testing a model is depicted in the following figure.</p>
<div id="fig-trainingproc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trainingproc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pictures/Training_proceedure.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trainingproc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Based on this <a href="https://developers.google.com/machine-learning/crash-course/overfitting/dividing-datasets">Google Developers Figure</a>
</figcaption>
</figure>
</div>
<p>Here, the training and validation data set are used in the training procedure and the testing data set in the testing procedure.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The reevaluation during training only makes sense when changing parameters can lead to an improvement. For a simple linear regression this is not the case, since once the model parameters <span class="math inline">\(\beta_0,...,\beta_n\)</span> are estimated, they are optimal (cf.&nbsp;<a href="https://en.wikipedia.org/wiki/Gauss-Markov_theorem">Gauss-Markov theorem</a>).</p>
</div>
</div>
<p>A simple training and test split with <span class="math inline">\(80\%\)</span> training data and <span class="math inline">\(20\%\)</span> test data can be generated with the <code>initial_split</code>, <code>training</code>, and <code>testing</code> function. Before splitting the data (which is done randomly) we can set a <em>seed</em>. Setting a seed allows us to reproduce the outcome of our code, even when randomness is involved.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tt_split<span class="ot">&lt;-</span><span class="fu">initial_split</span>(data_wine, <span class="fl">0.8</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> tt_split <span class="sc">%&gt;%</span> <span class="fu">training</span>() </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> tt_split <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Training the linear model on the training data and evaluating it on the test data then yields</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">formula =</span> alcohol <span class="sc">~</span>.,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> data_train</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(.pred,alcohol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rsq     standard       0.887
2 rmse    standard       0.408
3 mae     standard       0.307</code></pre>
</div>
</div>
</section>
<section id="cross-validation" class="level3" data-number="2.3.5">
<h3 data-number="2.3.5" class="anchored" data-anchor-id="cross-validation"><span class="header-section-number">2.3.5</span> Cross validation</h3>
<p>A popular approach we will use in most exercises extends the procedure described in Figure <a href="#fig-trainingsplit" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> and Figure <a href="#fig-trainingproc" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>. Instead of using a single training and validation data set, we create <strong>multiple instances</strong> of training and validation data by randomly assigning a data point to the training or validation set. More formally, <span class="math inline">\(v\)</span>-fold cross validation randomly splits the training and validation data into <span class="math inline">\(v\)</span> equally sized subsets. In each iteration, one of these subsets is set aside to be the validation data, while the other <span class="math inline">\(v-1\)</span> subsets are used for training. The figure below depicts how that process works for <code>v = 5</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pictures/grid_search_cv.png" class="img-fluid figure-img"></p>
<figcaption>5-fold Cross Validation</figcaption>
</figure>
</div>
<p>A part of the whole data set is left as testing data. The blue boxes in the lower part of the figure contain the validation (sub)sets for each split while the training data is contained in the remaining (sub)sets.</p>
<section id="creating-a-cross-validation-set-in-r" class="level4" data-number="2.3.5.1">
<h4 data-number="2.3.5.1" class="anchored" data-anchor-id="creating-a-cross-validation-set-in-r"><span class="header-section-number">2.3.5.1</span> Creating a cross validation set in R</h4>
<p>Cross validation in R can be performed using the <code>{resample}</code> library that is also part of the <code>{tidymodels}</code> framework.</p>
<p>The <code>vfold_cv</code> function creates a nested data frame, meaning that each entry in the data frame contains another data frame. <code>v</code> denotes the number of created folds and <code>data_train</code> specifies that the folds are created from the <code>data_train</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(data_train, <span class="at">v =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, that since the folds are also created stochastically, setting a seed ensures that the results are reproducible. We can access split <span class="math inline">\(i\)</span> in a fold using the <code>$split</code> attribute and double brackets with the respective index. Note, that each split consists of a training and validation set that can each be accessed using the <code>analysis</code> and <code>assessment</code> function respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>folds<span class="sc">$</span>splits[[<span class="dv">1</span>]] <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">analysis</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,134
Columns: 12
$ fixed.acidity        &lt;dbl&gt; 8.3, 7.7, 5.7, 7.2, 9.3, 6.6, 6.6, 9.0, 6.5, 7.2,…
$ volatile.acidity     &lt;dbl&gt; 0.25, 0.28, 0.26, 0.24, 0.34, 0.15, 0.17, 0.22, 0…
$ citric.acid          &lt;dbl&gt; 0.33, 0.58, 0.24, 0.29, 0.49, 0.32, 0.26, 0.49, 0…
$ residual.sugar       &lt;dbl&gt; 2.5, 12.1, 17.8, 2.2, 7.3, 6.0, 7.4, 10.4, 1.4, 5…
$ chlorides            &lt;dbl&gt; 0.053, 0.046, 0.059, 0.037, 0.052, 0.033, 0.052, …
$ free.sulfur.dioxide  &lt;dbl&gt; 12, 60, 23, 37, 30, 59, 45, 52, 14, 14, 44, 37, 2…
$ total.sulfur.dioxide &lt;dbl&gt; 72, 177, 124, 102, 146, 128, 128, 195, 99, 125, 1…
$ density              &lt;dbl&gt; 0.99404, 0.99830, 0.99773, 0.99200, 0.99800, 0.99…
$ pH                   &lt;dbl&gt; 2.89, 3.08, 3.30, 3.27, 3.17, 3.19, 3.16, 3.31, 3…
$ sulphates            &lt;dbl&gt; 0.48, 0.46, 0.50, 0.64, 0.61, 0.71, 0.37, 0.44, 0…
$ alcohol              &lt;dbl&gt; 9.5, 8.9, 10.1, 11.0, 10.2, 12.1, 10.0, 10.2, 10.…
$ quality              &lt;int&gt; 5, 5, 5, 7, 5, 8, 6, 6, 6, 5, 5, 5, 5, 6, 7, 6, 7…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>folds<span class="sc">$</span>splits[[<span class="dv">1</span>]] <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">assessment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 784
Columns: 12
$ fixed.acidity        &lt;dbl&gt; 6.2, 5.9, 6.7, 6.0, 8.6, 6.9, 8.0, 7.2, 6.7, 5.9,…
$ volatile.acidity     &lt;dbl&gt; 0.28, 0.32, 0.18, 0.29, 0.33, 0.21, 0.14, 0.19, 0…
$ citric.acid          &lt;dbl&gt; 0.45, 0.39, 0.28, 0.25, 0.34, 0.24, 0.49, 0.31, 0…
$ residual.sugar       &lt;dbl&gt; 7.50, 3.30, 10.20, 1.40, 11.80, 1.80, 1.50, 6.30,…
$ chlorides            &lt;dbl&gt; 0.045, 0.114, 0.039, 0.033, 0.059, 0.021, 0.035, …
$ free.sulfur.dioxide  &lt;dbl&gt; 46, 24, 29, 30, 42, 17, 42, 17, 32, 26, 50, 11, 1…
$ total.sulfur.dioxide &lt;dbl&gt; 203, 140, 115, 114, 240, 80, 120, 103, 111, 114, …
$ density              &lt;dbl&gt; 0.99573, 0.99340, 0.99469, 0.98794, 0.99882, 0.98…
$ pH                   &lt;dbl&gt; 3.26, 3.09, 3.11, 3.08, 3.17, 3.15, 3.26, 3.15, 3…
$ sulphates            &lt;dbl&gt; 0.46, 0.45, 0.45, 0.43, 0.52, 0.46, 0.40, 0.52, 0…
$ alcohol              &lt;dbl&gt; 9.2, 9.2, 10.9, 13.2, 10.0, 12.3, 10.6, 11.4, 11.…
$ quality              &lt;int&gt; 6, 6, 7, 6, 6, 7, 7, 7, 7, 6, 6, 4, 5, 5, 7, 8, 6…</code></pre>
</div>
</div>
</section>
<section id="training-a-model-using-cross-validation" class="level4" data-number="2.3.5.2">
<h4 data-number="2.3.5.2" class="anchored" data-anchor-id="training-a-model-using-cross-validation"><span class="header-section-number">2.3.5.2</span> Training a model using cross validation</h4>
<p>To train the linear model on each split, we can use the <code>fit_resamples</code> function. Training the model on each fold is the as simple as training he model without resamples: We simply pass the model specification, formula, and additionally the cross validation object into the <code>fit_resamples</code> formula. Additionally, we can also pass the metric set <code>multi_metric</code> to specify which metrics we want to use for model evaluation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling_res <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(lm_mod_resampling,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                            alcohol <span class="sc">~</span>.,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                            folds,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">metrics =</span> multi_metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The return value of the <code>fit_resamples</code> function is a data frame containing <span class="math inline">\(5\)</span> linear models (since we specified <code>v=5</code> when creating the folds object).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling_res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 5-fold cross-validation 
# A tibble: 5 × 4
  splits             id    .metrics         .notes          
  &lt;list&gt;             &lt;chr&gt; &lt;list&gt;           &lt;list&gt;          
1 &lt;split [3134/784]&gt; Fold1 &lt;tibble [3 × 4]&gt; &lt;tibble [0 × 3]&gt;
2 &lt;split [3134/784]&gt; Fold2 &lt;tibble [3 × 4]&gt; &lt;tibble [0 × 3]&gt;
3 &lt;split [3134/784]&gt; Fold3 &lt;tibble [3 × 4]&gt; &lt;tibble [0 × 3]&gt;
4 &lt;split [3135/783]&gt; Fold4 &lt;tibble [3 × 4]&gt; &lt;tibble [0 × 3]&gt;
5 &lt;split [3135/783]&gt; Fold5 &lt;tibble [3 × 4]&gt; &lt;tibble [0 × 3]&gt;</code></pre>
</div>
</div>
<p>We are mainly interested in the cross validation error (CV-RMSE) defined as</p>
<p><span class="math display">\[\begin{equation*}
  \mathrm{CV-RMSE} = \frac{1}{v}\sum_{i=1}^v \mathrm{RMSE}_i,
\end{equation*}\]</span></p>
<p>where <span class="math inline">\(\mathrm{RMSE}_i\)</span> stands for the RMSE of the <span class="math inline">\(i\)</span>-th. hold-out sample.</p>
<p>We can collect this metric by applying the <code>collect_metrics</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling_res <span class="sc">%&gt;%</span> <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  .metric .estimator  mean     n std_err .config             
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 mae     standard   0.300     5 0.00460 Preprocessor1_Model1
2 rmse    standard   0.451     5 0.0710  Preprocessor1_Model1
3 rsq     standard   0.866     5 0.0414  Preprocessor1_Model1</code></pre>
</div>
</div>
<p>The third column <code>mean</code> depicts the mean <code>rmse</code> and <code>rsq</code> across all the splits. Comparing the CV-RMSE (<span class="math inline">\(0.451\)</span>) to the true out of sample (OOS) RMSE of the test set (<span class="math inline">\(0.408\)</span>) reveals that the performance of the linear model seems stable, meaning that it is not prone to overfitting. Furthermore, the CV-RMSE seems to overestimate the true OOS RMSE, since <span class="math inline">\(0.451&gt;0.408\)</span>. Using this information we can make prediction about the alcohol contents of a wine with the estimated model parameters on the training data set.</p>
</section>
</section>
<section id="polynomial-regression-and-the-bias-variance-trade-off" class="level3" data-number="2.3.6">
<h3 data-number="2.3.6" class="anchored" data-anchor-id="polynomial-regression-and-the-bias-variance-trade-off"><span class="header-section-number">2.3.6</span> Polynomial regression and the bias variance trade off</h3>
<p>Polynomial regression is a special case of multiple linear regression where the model is still linear in its coefficients but the dependent variable <span class="math inline">\(y\)</span> is modeled as polynomial in <span class="math inline">\(x\)</span>. For an <span class="math inline">\(n\)</span>-th degree polynomial model the model equation is therefore given by</p>
<p><span class="math display">\[\begin{equation*}
  y = \beta_0 + \beta_1 x + \beta_2 x^2 + ... + \beta_n x^n.
\end{equation*}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For this specific model we only use one independent variable <span class="math inline">\(x\)</span> instead of <span class="math inline">\(n\)</span> different independent variables <span class="math inline">\(x_1\)</span>,…,<span class="math inline">\(x_n\)</span>.</p>
</div>
</div>
<p>Say, we want to model the alcohol contents of wine with a MLR model using the wine density as the only predictor.</p>
<p>Consider the following synthetic dataset consisting of <span class="math inline">\(12\)</span> observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>data_synth <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">11</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> x<span class="sc">+</span><span class="fu">rnorm</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.1</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>split_synth <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data_synth,<span class="fl">0.8</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>data_train_synth <span class="ot">&lt;-</span> split_synth <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>data_test_synth <span class="ot">&lt;-</span> split_synth <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>data_synth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
        x       y
    &lt;dbl&gt;   &lt;dbl&gt;
 1 0      -0.0560
 2 0.0909  0.0679
 3 0.182   0.338 
 4 0.273   0.280 
 5 0.364   0.377 
 6 0.455   0.626 
 7 0.545   0.592 
 8 0.636   0.510 
 9 0.727   0.659 
10 0.818   0.774 
11 0.909   1.03  
12 1       1.04  </code></pre>
</div>
</div>
<p>From the figure below, it is immediately evident, that a polynomial model perfectly fits the training data, but severely fails to estimate the rightmost point of the testing data. While the linear model does not fit the training data</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_linear_models_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To verify this, we can also compare the training and test error for different metrics of each model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>lm_poly_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">8</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data_train_synth</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>lm_lin_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data_train_synth</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualizing the difference in train and test error then yields</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_linear_models_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The example above demonstrates the phenomenon of bias-variance tradeoff. A low variance and high bias can be observed in the linear model, since there are only few (<em>two</em>) model parameters and a small discrepancy between training and test error. The polynomial model exhibits a large discrepancy between training and test error and since there are many (<em>nine</em>) parameters, indicating that it has a high variance but low bias.</p>
</section>
</section>
<section id="exercises" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="exercises"><span class="header-section-number">2.4</span> Exercises</h2>
<p>Throughout the exercises, we will work with a subset of the <a href="https://www.kaggle.com/datasets/corrieaar/apartment-rental-offers-in-germany">Apartment rental offers in Germany</a> data set that can be downloaded using the button below. It contains 239 unique rental listings for flats in Augsburg which were sourced at three different dates in 2018 and 2019 and contains 28 different variables.</p>
<div style="text-align: center;">
<p><a href="data/rent_aux.csv" class="btn btn-outline-primary" role="button" data-toggle="tooltip" title="1.2 MB">Download AugsburgRental</a></p>
</div>
<div id="exr-DEA1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.1</strong></span> Instead of focusing on a comprehensive data cleaning and manipulation process, we will simply use the two variables <code>livingSpace</code> measuring the area of living in <span class="math inline">\(m^2\)</span> of a listing and <code>baseRent</code> in EUR, representing the monthly base rent.</p>
<p>Import the data and visualize the relationship between the two variables <code>livingSpace</code> and <code>baseRent</code> with a scatter plot. Rename the axis of the plot such that they display the words <code>base rent</code> and <code>living space</code> (seperated by a whitespace).</p>
</div>
<div id="exr-DEA2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.2</strong></span> Without conducting a thorough outlier analysis, remove every listing that either costs more than <span class="math inline">\(2500\)</span> EUR or is bigger than <span class="math inline">\(200\: m^2\)</span>.</p>
</div>
<div id="exr-split" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.3</strong></span> Create a training (<span class="math inline">\(80\%\)</span>) and test data set using the filtered data. Use <code>set.seed(2)</code> to generate reproducible results.</p>
</div>
<div id="exr-linear_model1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.4</strong></span> Train a simple linear model on the training data.</p>
</div>
<div id="exr-linear_model2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.5</strong></span> Generate a model summary and interpret the coefficients. Is the independent variable statistically significant?</p>
</div>
<div id="exr-linear_model3" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.6</strong></span> Evaluate the model on the test data by considering the adjusted <span class="math inline">\(R^2\)</span> and MAE. On average, how far off is the estimated base rent?</p>
</div>
<div id="exr-linear_model4" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.7</strong></span> Create a <span class="math inline">\(10\)</span>-fold cross validation split of the training data using the same seed as before and retrain the simple linear model. Compare the cross validation MAE to the OOS MAE and interpret the result.</p>
</div>
<div id="exr-linear_model4" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.8</strong></span> Repeat Exercises <a href="#exr-linear_model3" class="quarto-xref">Exercise&nbsp;<span>2.6</span></a> and <a href="#exr-linear_model4" class="quarto-xref">Exercise&nbsp;<span>2.8</span></a> for a polynomial model of degree 20. Compare the test and cross-validation MAE of the linear model with the polynomial model.</p>
</div>
<div id="exr-linear_model5" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.9</strong></span> Create a scatter plot of the training data and insert both fitted curves using the <code>geom_smooth</code> function.</p>
</div>
<div id="exr-theoretical1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.10</strong></span> Assume we have fitted a simple linear model <span class="math display">\[\begin{equation*}
  \hat{y} = \hat{\beta_0}+\hat{\beta_1}x.
\end{equation*}\]</span></p>
<p>For <span class="math inline">\(\hat\beta_1\)</span> the <span class="math inline">\(t\)</span>-statistic has a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(1e-16\)</span> (<span class="math inline">\(=1\cdot 10^{-16}\)</span>). Describe the null hypothesis of the underlying test and explain what concnulision can be drawn based on this <span class="math inline">\(p\)</span>-value.</p>
</div>
<div id="exr-theoretical2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.11</strong></span> Assume we have a data set with <span class="math inline">\(k = 400\)</span> containing a single independent variable <span class="math inline">\(x\)</span> and a real valued dependent variable <span class="math inline">\(y\)</span>. We fit a simple regression model and a polynomial regression with degree <span class="math inline">\(5\)</span> on <span class="math inline">\(75\%\)</span> of the data and leave the remaining <span class="math inline">\(25\%\)</span> for testing .</p>
<ol type="1">
<li><p>Assume that the true relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is linear. Consider the training RMSE for the linear regression, and also the training RMSE for the polynomial regression. Choose the most appropriate answer and justify your choice.</p>
<p>1.1 The polynomial model has more flexibility due to the additional terms, so it will fit the data better than the linear model, resulting in a lower training RMSE.</p>
<p>1.2 The linear model is simpler and less prone to overfitting, so it will produce a lower training RMSE compared to the polynomial model.</p>
<p>1.3 Since both models are trying to explain the same data, their training RMSE should be approximately the same.</p>
<p>1.4 Without knowing the true underlying relationship between the predictor and response, we cannot definitively predict the behavior of the training RMSE for either model.</p></li>
<li><p>Repeat the previous exercise but instead of the training RMSE, consider the test RMSE.</p></li>
</ol>
</div>
</section>
<section id="solutions" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="solutions"><span class="header-section-number">2.5</span> Solutions</h2>
<div id="sol-DEA1" class="proof solution">
<p><span class="proof-title"><em>Solution 2.1</em> (<a href="#exr-DEA1" class="quarto-xref">Exercise&nbsp;<span>2.1</span></a>). </span>The data set can be imported using the <code>read_csv</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data_aux <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rent_aux.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>ggplot</code> function, we can create a simple scatter plot. The <code>labs</code> function allows to define new axis labels by specifying the axis and assigning the names to the respective axis. <span class="math inline">\(x\)</span> corresponds to the horizontal axis and <span class="math inline">\(y\)</span> to the vertical axis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data_aux <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> livingSpace, <span class="at">y =</span> baseRent)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"living space"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"base rent"</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_linear_models_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="sol-DEA2" class="proof solution">
<p><span class="proof-title"><em>Solution 2.2</em> (<a href="#exr-DEA2" class="quarto-xref">Exercise&nbsp;<span>2.2</span></a>). </span>To select all listings with base rent lower than <span class="math inline">\(2500\)</span> EUR and living space less than <span class="math inline">\(200\)</span> sqm, we can use the <code>filter</code> function and overwrite the old data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>data_aux <span class="ot">&lt;-</span> data_aux <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(baseRent <span class="sc">&lt;=</span> <span class="dv">2500</span>, livingSpace <span class="sc">&lt;=</span> <span class="dv">200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="sol-split" class="proof solution">
<p><span class="proof-title"><em>Solution 2.3</em> (<a href="#exr-split" class="quarto-xref">Exercise&nbsp;<span>2.3</span></a>). </span>By setting <code>set.seed(2)</code> we can make sure that the following results are reproducible. Similar to <a href="#sec-tts" class="quarto-xref"><span>Section 2.3.4</span></a>, we can define a split object using the <code>initial_split</code> function and select the training and test portion using the <code>training</code> and <code>testing</code> functions respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span><span class="fu">initial_split</span>(data_aux,<span class="fl">0.8</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> split <span class="sc">%&gt;%</span> <span class="fu">training</span>(split)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> split <span class="sc">%&gt;%</span> <span class="fu">testing</span>(split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="sol-linear_model1" class="proof solution">
<p><span class="proof-title"><em>Solution 2.4</em> (<a href="#exr-linear_model1" class="quarto-xref">Exercise&nbsp;<span>2.4</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(baseRent <span class="sc">~</span> livingSpace, data_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="sol-linear_model2" class="proof solution">
<p><span class="proof-title"><em>Solution 2.5</em> (<a href="#exr-linear_model2" class="quarto-xref">Exercise&nbsp;<span>2.5</span></a>). </span>A simple model summary can be created by passing the trained model into the <code>tidy</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     87.3    25.2        3.46 6.58e- 4
2 livingSpace     10.4     0.322     32.2  5.49e-79</code></pre>
</div>
</div>
<p>The estimated parameter <span class="math inline">\(\hat{\beta_1} = 10.4\)</span> indicates that according to the linear model, we expect the base rent to rise <span class="math inline">\(10.4\)</span> EUR for every additional square meter of living space.</p>
</div>
<div id="sol-linear_model3" class="proof solution">
<p><span class="proof-title"><em>Solution 2.6</em> (<a href="#exr-linear_model3" class="quarto-xref">Exercise&nbsp;<span>2.6</span></a>). </span>We can calculate the adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(MAE\)</span> using the <code>metric_set</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>multi_metric<span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rsq,mae)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(.pred,baseRent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rsq     standard       0.883
2 mae     standard     108.   </code></pre>
</div>
</div>
<p>MAE<span class="math inline">\(=108\)</span> indicates that on average our estimated base rent is off by <span class="math inline">\(108\)</span> EUR.</p>
</div>
<div id="sol-linear_model4" class="proof solution">
<p><span class="proof-title"><em>Solution 2.8</em> (<a href="#exr-linear_model4" class="quarto-xref">Exercise&nbsp;<span>2.8</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(data_train)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling_res <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(baseRent <span class="sc">~</span> livingSpace,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                folds,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">metrics =</span> multi_metric)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>lm_mod_resampling_res <span class="sc">%&gt;%</span> <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator    mean     n std_err .config             
  &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
1 mae     standard   116.       10  5.12   Preprocessor1_Model1
2 rsq     standard     0.869    10  0.0153 Preprocessor1_Model1</code></pre>
</div>
</div>
<p>The cross-validation MAE of <span class="math inline">\(116\)</span> EUR compared to the test MAE of <span class="math inline">\(108\)</span> EUR indicates that the cross-validation error is overestimating the true test error. This is in fact favorable, since it is preferable to have a pessimistic bias towards an estimated error. In other words, overestimating an error is always better than underestimating an error.</p>
</div>
<div id="sol-linear_model4" class="proof solution">
<p><span class="proof-title"><em>Solution 2.8</em> (<a href="#exr-linear_model4" class="quarto-xref">Exercise&nbsp;<span>2.8</span></a>). </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lm_poly_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> baseRent <span class="sc">~</span> <span class="fu">poly</span>(livingSpace, <span class="dv">20</span>), </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_train</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>lm_poly_mod <span class="sc">%&gt;%</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(data_test) <span class="sc">%&gt;%</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multi_metric</span>(.pred,baseRent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rsq     standard       0.349
2 mae     standard     153.   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lm_poly_mod_resampling_res <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(baseRent <span class="sc">~</span> <span class="fu">poly</span>(livingSpace,<span class="dv">20</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                folds,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">metrics =</span> multi_metric)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>lm_poly_mod_resampling_res <span class="sc">%&gt;%</span> <span class="fu">collect_metrics</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n   std_err .config             
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;               
1 mae     standard   1541.       10 1205.     Preprocessor1_Model1
2 rsq     standard      0.624    10    0.0937 Preprocessor1_Model1</code></pre>
</div>
</div>
<p>Compared to the simple linear model, the polynomial model performs a lot worse on the test data as it severely ovefits on the training data. The CV MAE of <span class="math inline">\(1541\)</span> compared to the test MAE of <span class="math inline">\(153\)</span> is another redflag we should consider when evaluating model performance.</p>
</div>
<div id="sol-linear_model5" class="proof solution">
<p><span class="proof-title"><em>Solution 2.9</em> (<a href="#exr-linear_model5" class="quarto-xref">Exercise&nbsp;<span>2.9</span></a>). </span>We can directly pipe the training data <code>data_train</code> into the <code>ggplot</code> function to create the plot. The <code>color</code> argument in the <code>geom_point</code> function changes the color of the points and the <code>size</code> argument toggles the point sizes in the figure. When using <code>geom_smooth</code> have to express the formula in terms of <code>x</code> and <code>y</code> instead of using <code>livingSpace</code> and <code>baseRent</code>. Setting <code>se=FALSE</code> removes the confidence band of the estimated lines. <code>color = "black"</code>, <code>linetype=2</code>, and <code>linewidth=1.5</code> specifies the visual characteristics of the line. As with the previous plot, we can also change the axis labels using <code>labs</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>data_train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>livingSpace,<span class="at">y=</span>baseRent))<span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"#f07167"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">20</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype=</span> <span class="dv">2</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype=</span> <span class="dv">5</span>,</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Living space in sqm"</span>,</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"base rent in EUR"</span>)<span class="sc">+</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02_linear_models_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="sol-theoretical1" class="proof solution">
<p><span class="proof-title"><em>Solution 2.10</em> (<a href="#exr-theoretical1" class="quarto-xref">Exercise&nbsp;<span>2.10</span></a>). </span>A <span class="math inline">\(p\)</span>-value of <span class="math inline">\(1e-16\)</span> (<span class="math inline">\(=1\cdot 10^{-16}\)</span>) indicates that we can reject the null hypotheses <span class="math inline">\(H_0: \beta_1 = 0\)</span> to the significance level <span class="math inline">\(1-(10^{-16})\)</span>.</p>
</div>
<div id="sol-theoretical2" class="proof solution">
<p><span class="proof-title"><em>Solution 2.11</em> (<a href="#exr-theoretical2" class="quarto-xref">Exercise&nbsp;<span>2.11</span></a>). </span></p>
<ol type="1">
<li><p>Since the polynomial model has more flexibility due to the additional terms, it will likely fit the training data better than the linear model, resulting in a lower training RMSE.</p></li>
<li><p>The linear model is simpler and less prone to overfitting, so it will likely produce a lower test RMSE compared to the polynomial model.</p></li>
</ol>
</div>
</section>
<section id="session-info" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="session-info"><span class="header-section-number">2.6</span> Session Info</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggtext_0.1.2       yardstick_1.3.1    workflowsets_1.1.0 workflows_1.1.4   
 [5] tune_1.2.1         rsample_1.2.1      recipes_1.0.10     parsnip_1.2.1     
 [9] modeldata_1.3.0    infer_1.0.7        dials_1.2.1        scales_1.3.0      
[13] broom_1.0.5        tidymodels_1.2.0   lubridate_1.9.3    forcats_1.0.0     
[17] stringr_1.5.1      dplyr_1.1.4        purrr_1.0.2        readr_2.1.5       
[21] tidyr_1.3.1        tibble_3.2.1       ggplot2_3.5.1      tidyverse_2.0.0   

loaded via a namespace (and not attached):
 [1] rlang_1.1.3         magrittr_2.0.3      furrr_0.3.1        
 [4] compiler_4.4.0      mgcv_1.9-1          vctrs_0.6.5        
 [7] lhs_1.1.6           pkgconfig_2.0.3     crayon_1.5.2       
[10] fastmap_1.1.1       backports_1.4.1     labeling_0.4.3     
[13] utf8_1.2.4          rmarkdown_2.26      prodlim_2023.08.28 
[16] markdown_1.12       tzdb_0.4.0          bit_4.0.5          
[19] xfun_0.43           jsonlite_1.8.8      parallel_4.4.0     
[22] R6_2.5.1            stringi_1.8.4       parallelly_1.37.1  
[25] rpart_4.1.23        Rcpp_1.0.12         iterators_1.0.14   
[28] knitr_1.46          future.apply_1.11.2 Matrix_1.7-0       
[31] splines_4.4.0       nnet_7.3-19         timechange_0.3.0   
[34] tidyselect_1.2.1    rstudioapi_0.16.0   yaml_2.3.8         
[37] timeDate_4032.109   codetools_0.2-20    listenv_0.9.1      
[40] lattice_0.22-6      withr_3.0.0         evaluate_0.23      
[43] future_1.33.2       survival_3.5-8      xml2_1.3.6         
[46] pillar_1.9.0        foreach_1.5.2       generics_0.1.3     
[49] vroom_1.6.5         hms_1.1.3           munsell_0.5.1      
[52] commonmark_1.9.1    globals_0.16.3      class_7.3-22       
[55] glue_1.7.0          tools_4.4.0         data.table_1.15.4  
[58] modelenv_0.1.1      gower_1.0.1         grid_4.4.0         
[61] ipred_0.9-14        colorspace_2.1-0    nlme_3.1-164       
[64] cli_3.6.2           DiceDesign_1.10     fansi_1.0.6        
[67] lava_1.8.0          gtable_0.3.5        GPfit_1.0-8        
[70] digest_0.6.35       htmlwidgets_1.6.4   farver_2.1.1       
[73] htmltools_0.5.8.1   lifecycle_1.0.4     hardhat_1.3.1      
[76] gridtext_0.1.5      bit64_4.0.5         MASS_7.3-60.2      </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01_prerequisites.html" class="pagination-link" aria-label="Important R concepts">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Important R concepts</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_regularization.html" class="pagination-link" aria-label="Regularization">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regularization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>